apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "blockscout-v2-frontend.fullname" . }}
  labels:
    {{- include "blockscout-v2-frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "blockscout-v2-frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "blockscout-v2-frontend.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "blockscout-v2-frontend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-stats
          image: "{{ .Values.image.stats.repository }}:{{ .Values.image.stats.tag }}"
          resources:
            {{- toYaml .Values.resources.stats | nindent 12 }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: stats-http
              containerPort: {{ .Values.service.bs_stats_http }}
              protocol: TCP
            - name: stats-metrics
              containerPort: {{ .Values.service.bs_stats_metrics }}
              protocol: TCP
          env:
{{- include "stats_env" . | indent 10 }}
          {{- if .Values.readinessProbe.stats.enable }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.stats.path }}
              port: stats-http
              scheme: HTTP
              {{- with .Values.readinessProbe.stats.params }}
              {{- . | toYaml | nindent 12 }}
              {{- end }}
          {{- end }}
          {{- if .Values.livenessProbe.stats.enable }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.stats.path }}
              port: stats-http
              scheme: HTTP
              {{- with .Values.livenessProbe.stats.params }}
              {{- . | toYaml | nindent 12 }}
              {{- end }}
          {{- end }}
        - name: {{ .Chart.Name }}-frontend
          image: "{{ .Values.image.frontend.repository }}:{{ .Values.image.frontend.tag }}"
          resources:
            {{- toYaml .Values.resources.frontend | nindent 12 }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: frontend-http
              containerPort: {{ .Values.service.bs_frontend }}
              protocol: TCP
          env:
          {{- include "frontend_env" . | indent 10 }}
          {{- if .Values.readinessProbe.frontend.enable }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.frontend.path }}
              port: frontend-http
              scheme: HTTP
             {{- with .Values.readinessProbe.frontend.params }}
             {{ . | toYaml | nindent 12 }}
             {{- end }}
             {{- end }}
          {{- if .Values.livenessProbe.frontend.enable }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.frontend.path }}
              port: frontend-http
              scheme: HTTP
              {{- with .Values.livenessProbe.frontend.params }}
              {{ . | toYaml | nindent 12 }}
              {{- end }}
         {{- end }}
      volumes:
        - name: postgredb
        {{- if and .Values.persistence.enabled (not .Values.persistence.hostPath) }}
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ template "blockscout-v2-frontend.fullname" . }}{{- end }}
        {{- else if and .Values.persistence.enabled .Values.persistence.hostPath }}
          hostPath:
            path: {{ .Values.persistence.hostPath }}
            type: DirectoryOrCreate
        {{- else }}
          emptyDir: {}
        {{- end }}
        - name: entrypoint
          emptyDir: {}
        - name: scripts
          configMap:
            name: {{ include "blockscout-v2-frontend.fullname" . }}-scripts
            defaultMode: 0777

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ . | toYaml | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
