# Default values for narada-eddsa.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

net: stagenet

ethSuggestedFeeVersion:
  mainnet: 1
  stagenet: 2
  testnet: 2
  mocknet: 1

narada_log_level: "info"

signer:
  name: hermeschain
  password: ""
  mnemonicSecret: ""
  passwordSecret: ""

chain_home_folder: /root/.hermesnode

environment:
  TSS_P2P_PORT: 5042
  P2P_ID_PORT: 6042
  EDDSA_HTTP_PORT: 6050


# use in multi nodes envs
eddsa_peer:

external_ip:

debug: true

dojima_chain:
  rpc_url: http://dojima-chain:8545
  grpc_url: hermesnode:9090
  chain_id: 1401

hermesApi: hermesnode:1317
chainID:
  testnet: hermeschain-stagenet
#  mainnet: thorchain-mainnet-v1
#  stagenet: thorchain-stagenet-v2
#  mocknet: hermes_mocknet

hermesDaemon:
#  mainnet: hermesnode:27147
  testnet: hermesnode:26657
#  stagenet: hermesnode:27147
#  mocknet: hermesnode:26657


replicaCount: 1

strategyType: Recreate

image:
  repository: asia-south1-docker.pkg.dev/prod-dojima/testnet/hermes
  pullPolicy: IfNotPresent
  tag: 76910312_3.0.2
  hash: "af37838a6800e4e866c4e42e2aace980ccdd6861bd983eb94dfc015a15f8ed39" # Not used for mocknet/testnet

imagePullSecrets: []
nameOverride: "narada-eddsa"
fullnameOverride: "narada-eddsa"

persistence:
  enabled: true
  size:
    testnet: 10Gi
#    mainnet: 50Gi
    stagenet: 1Gi
#    mocknet: 10Gi
  accessMode: ReadWriteOnce
  # existingClaim: your-pvc
#  storageClass: gp2
  # hostPath: /host-path

service:
  type: ClusterIP
  port:
    tss_p2p: 5042
    p2p_id: 6042
    eddsa_http: 6050
    prometheus: 9000

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "serv-node-narada-eddsa"

priorityClassName: ""

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# service:
#   type: ClusterIP
#   port: 80

resources:
  requests:
    cpu: 1
    memory: 1Gi
  limits:
    memory: 1Gi

nodeSelector: {}

tolerations: []

affinity: {}

global:
  gateway:
    enabled: false
  images:
    alpineK8s:
      tag: 1.18.2
      hash: 768491682ca99e14498ddb62973a95a664a0525ca18e7ad0eaab2621d3124f5b
    busybox:
      tag: latest
      hash: caa382c432891547782ce7140fb3b7304613d3b0438834dce1cad68896ab110a


preparam: ""