loki:
  config:
    chunk_store_config:
      max_look_back_period: 1440h
    table_manager:
      retention_deletes_enabled: true
      retention_period: 1440h

  persistence:
    enabled: true
    size: 20Gi
