apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "blockscout-v2-backend.fullname" . }}
  labels:
    {{- include "blockscout-v2-backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "blockscout-v2-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "blockscout-v2-backend.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "blockscout-v2-backend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-postgres
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "blockscout-v2-backend-postgres.image" . }}
          args:
            - -c
            - max_connections=20000
            - -c
            - shared_buffers=2048MB
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: postgredb
              mountPath: /var/lib/postgresql/data
              subPath: postgres
              {{- range $key, $value := .Values.postgres.files.list }}
            - mountPath: {{ $.Values.postgres.files.mountPath }}/{{ $key }}
              name: scripts
              subPath: {{ $key }}
              {{- end }}
          env:
            - name: POSTGRES_PASSWORD
              value: {{ .Values.env.pg_pass }}
            - name: POSTGRES_USER
              value: {{ .Values.env.pg_user }}
            - name: POSTGRES_HOST_AUTH_METHOD
              value: {{ .Values.env.pg_host_auth_method }}
          ports:
            - name: postgres
              containerPort: {{ .Values.service.postgres }}
              protocol: TCP
          {{- if .Values.readinessProbe.postgres.enable }}
          readinessProbe:
            exec:
              command:
                - psql
                - -U
                - {{ .Values.env.pg_user }}
                - -d
                - {{ .Values.env.pg_db_name }}
                - -c
                - "SELECT 1"
            timeoutSeconds: 2
            initialDelaySeconds: 10
          {{- end }}
          resources:
            {{- toYaml .Values.resources.postgres | nindent 12 }}
        - name: smart-contract-verifier
          image: {{ include "blockscout-v2-backend-rs.image" . }}
          imagePullPolicy: IfNotPresent
          env:
            {{- range $key, $value := .Values.bs_rs_env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.service.bs_rs }}
              name: bs-rs-http
              protocol: TCP
          {{- if .Values.livenessProbe.sc.enable }}
          livenessProbe:
            httpGet:
              path: /health
              port: bs-rs-http
          {{- end }}
          {{- if .Values.readinessProbe.sc.enable }}
          readinessProbe:
            httpGet:
              path: /health
              port: bs-rs-http
          {{- end }}
          volumeMounts:
            - mountPath: /app/config
              name: scripts
          resources:
            {{- toYaml .Values.resources.smart_contract_verifier | nindent 12 }}
        - name: {{ .Chart.Name }}-backend
          image: {{ include "blockscout-v2-backend-blockscout.image" . }}
          imagePullPolicy: IfNotPresent
          resources:
            {{- toYaml .Values.resources.blockscout | nindent 12 }}
          ports:
            - name: bs-http
              containerPort: {{ .Values.service.bs }}
              protocol: TCP
          {{- with .Values.commands.blockscout.command }}
          command: {{ . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.commands.blockscout.args }}
          args: {{ . | toYaml | nindent 12 }}
          {{- end }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range $key, $value := .Values.blockscout }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            - name: BLOCKSCOUT_HOST
              value: {{ .Values.blockscout_host | quote }}
          {{- if .Values.readinessProbe.blockscout.enable }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.blockscout.path }}
              port: bs-http
              scheme: HTTP
              {{- with .Values.readinessProbe.blockscout.params }}
              {{- . | toYaml | nindent 12 }}
              {{- end }}
          {{- end }}
          {{- if .Values.livenessProbe.blockscout.enable }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.blockscout.path }}
              port: bs-http
              scheme: HTTP
              {{- with .Values.livenessProbe.blockscout.params }}
              {{- . | toYaml | nindent 12 }}
              {{- end }}
          {{- end }}
      volumes:
        - name: postgredb
        {{- if and .Values.persistence.enabled (not .Values.persistence.hostPath) }}
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ template "blockscout-v2-backend.fullname" . }}{{- end }}
        {{- else if and .Values.persistence.enabled .Values.persistence.hostPath }}
          hostPath:
            path: {{ .Values.persistence.hostPath }}
            type: DirectoryOrCreate
        {{- else }}
          emptyDir: {}
        {{- end }}
        - name: entrypoint
          emptyDir: {}
        - name: scripts
          configMap:
            name: {{ include "blockscout-v2-backend.fullname" . }}-scripts
            defaultMode: 0777

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ . | toYaml | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
