apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dojima-blockscout.fullname" . }}
  labels:
    {{- include "dojima-blockscout.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "dojima-blockscout.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dojima-blockscout.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "dojima-blockscout.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: postgres
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "dojima-blockscout-postgres.image" . }}
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_PASSWORD
              value: {{ .Values.env.pg_pass }}
            - name: POSTGRES_USER
              value: {{ .Values.env.pg_user }}
            - name: POSTGRES_HOST_AUTH_METHOD
              value: {{ .Values.env.pg_host_auth_method }}
            - name: PGDATA
              value: /var/lib/postgresql/data/blockscout
          ports:
            - name: postgres
              containerPort: {{ .Values.service.postgres }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: {{ .Chart.Name }}
          image: {{ include "dojima-blockscout-blockscout.image" . }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: bs
              containerPort: {{ .Values.service.bs }}
              protocol: TCP
          command:
            - bash
            - -c
            - "./bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && ./bin/blockscout start"
          env:
            - name: ETHEREUM_JSONRPC_VARIANT
              value: {{ .Values.env.eth_json_var }}
            - name: COIN
              value: {{ .Values.env.coin}}
            - name: CHAIN_ID
              value: "{{ .Values.env.chain_id }}"
            - name: SECRET_KEY_BASE
              value: "{{ .Values.env.secret_key }}"
            - name: ETHEREUM_JSON_HTTP_URL
              value: {{ .Values.env.eth_json_http }}
            - name: DATABASE_URL
              value: {{ .Values.env.database_url }}
            - name: MIX_ENV
              value: {{ .Values.env.mix_env }}
            - name: ECTO_USE_SSL
              value: "{{ .Values.env.ecto_use_ssl }}"
            - name: PORT
              value: "{{ .Values.service.bs }}"
            - name: INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER
              value: "{{ .Values.env.indexer_dis_pending_fetcher}}"
            - name: ETHEREUM_JSONRPC_TRACE_URL
              value: "{{ .Values.env.eth_json_http }}"
            - name: ETHEREUM_JSONRPC_WS_URL
              value: "{{ .Values.env.eth_ws_url }}"
            - name: ETHEREUM_JSONRPC_TRANSPORT
              value: "{{ .Values.env.eth_jsonrpc_transport }}"
            - name: NETWORK
              value: {{ .Values.env.network }}
            - name: SUBNETWORK
              value: {{ .Values.env.sub_network }}
            - name: COIN_NAME
              value: {{ .Values.env.coin_name }}
            - name: CACHE_TXS_COUNT_PERIOD
              value: "{{ .Values.env.cache_tx_count_period }}"
            - name: CACHE_BLOCK_COUNT_PERIOD
              value: "{{ .Values.env.cache_block_count_period }}"
            - name: POOL_SIZE
              value: "{{ .Values.env.pool_size }}"
            - name: POOL_SIZE_API
              value: "{{ .Values.env.pool_size_api}}"
            - name: BLOCKSCOUT_HOST
              value: {{ .Values.env.blockscout_host }}
            - name: SUPPORTED_CHAINS
              value: "{{ .Values.env.supported_chains }}"
            - name: SHOW_PRICE_CHART
              value: "{{ .Values.env.show_price_chart }}"
            - name: SHOW_TXS_CHART
              value: "{{ .Values.env.show_txs_chart }}"
            - name: ENABLE_TXS_STATS
              value: "{{ .Values.env.enable_tx_stats }}"
            - name: HISTORY_FETCH_INTERVAL
              value: "{{ .Values.env.history_fetch_interval }}"
            - name: APPS_MENU
              value: "{{ .Values.env.apps_menu }}"
            - name: DISPLAY_TOKEN_ICONS
              value: "{{ .Values.env.display_token_icons }}"
            - name: API_RATE_LIMIT
              value: "{{ .Values.env.api_rate_limit }}"
            - name: API_RATE_LIMIT_BY_KEY
              value: "{{ .Values.env.api_rate_limit_by_key }}"
            - name: API_RATE_LIMIT_BY_IP
              value: "{{ .Values.env.api_rate_limit_by_ip }}"
            - name: INDEXER_MEMORY_LIMIT
              value: "{{ .Values.env.indexer_memory_limit }}"
      volumes:
        - name: data
        {{- if and .Values.persistence.enabled (not .Values.persistence.hostPath) }}
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ template "dojima-blockscout.fullname" . }}{{- end }}
        {{- else if and .Values.persistence.enabled .Values.persistence.hostPath }}
          hostPath:
            path: {{ .Values.persistence.hostPath }}
            type: DirectoryOrCreate
        {{- else }}
          emptyDir: {}
        {{- end }}
        - name: entrypoint
          emptyDir: {}
        - name: scripts
          configMap:
            name: {{ include "dojima-blockscout.fullname" . }}-scripts
            defaultMode: 0777

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
