apiVersion: v1
kind: Service
metadata:
  name: {{ include "dojima-blockscout.fullname" . }}
  labels:
    {{- include "dojima-blockscout.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.postgres }}
      targetPort: postgres
      protocol: TCP
      name: postgres
    - port: {{ .Values.service.bs }}
      targetPort: bs
      protocol: TCP
      name: bs
  selector:
    {{- include "dojima-blockscout.selectorLabels" . | nindent 4 }}
