{{- if .Values.dojimaSnapshot.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: dojima-snapshot
spec:
  schedule: {{ .Values.dojimaSnapshot.schedule | quote }}
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          activeDeadlineSeconds: {{ .Values.dojimaSnapshot.activeDeadlineSeconds }}
          serviceAccountName: dojima-snapshot
          containers:
            - name: dojima-snapshot
              image: {{ .Values.dojimaSnapshot.image.name }}:{{ .Values.dojimaSnapshot.image.tag }}@sha256:{{ .Values.dojimaSnapshot.image.hash }}
              env:
                {{- range $key, $value := .Values.dojimaSnapshot.env }}
                - name: {{ $key }}
                  value: {{ $value | quote }}
                {{- end }}
                - name: MINIO_IMAGE
                  value: {{ .Values.minio.image.name }}:{{ .Values.minio.image.tag }}@sha256:{{ .Values.minio.image.hash }}
                {{- range $key, $value := .Values.dojimaSnapshot.secretEnv }}
                - name: {{ $key }}
                  valueFrom:
                    secretKeyRef:
                      key: {{ $value | quote }}
                      name: provider
                {{- end }}
          restartPolicy: Never
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dojima-snapshot
rules:
  - apiGroups: [""]
    resources: [pods]
    verbs: [get, create, patch, delete, update, list, watch]
  - apiGroups: [""]
    resources: [pods/log]
    verbs: [get]
  - apiGroups: [snapshot.storage.k8s.io]
    resources: [volumesnapshots]
    verbs: [delete, get, create]
  - apiGroups: [""]
    resources: [persistentvolumeclaims]
    verbs: [delete, get, create, update]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dojima-snapshot
subjects:
  - kind: ServiceAccount
    name: dojima-snapshot
    apiGroup: ""
roleRef:
  kind: Role
  name: dojima-snapshot
  apiGroup: ""
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dojima-snapshot
{{- end }}
