# Default values for gateway.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

net: testnet


# whitelistIPs contains a list of allowed IP addresses or CIDRs. Defaults to allow all
# traffic if not provided.
whitelistIPs: []

replicaCount: 1

image:
  name: nginx
  tag: 1.21.0-alpine
  hash: cc8c413c74aba9fef9dae7f3da736725136bad1e3f24fbc93788aea1944f51c4

imagePullSecrets: []
# used for gateway.name
nameOverride: "backend-gateway"
# used for gateway.fullname
fullnameOverride: "f-backend-gateway"

domain:
  faucet:
    api: faucet.h4s.dojima.network
    enable: true
  fiber:
    testnet:
      api: fiber-test.h4s.dojima.network
      enable: true

service:
  type: ClusterIP
  port:
    faucet:
      testnet:
        api: 8040
    fiber:
      testnet:
        api: 7050

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "serv-backend-gateway"

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # cert-manager.io/cluster-issuer: letsencrypt-production
  hosts: []
    # - host: midgard.example.com
    #   paths:
    #   - path: /
    #     backend:
    #       serviceName: gateway
    #       servicePort: midgard
  tls: []
    # - secretName: midgard-tls
    #   hosts:
    #     - midgard.example.com

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  limits:
    cpu: 0.05
    memory: 50Mi
  requests:
    cpu: 0.01
    memory: 20Mi

nodeSelector: {}

tolerations: []

affinity: {}

global:
  net:
  images:
    alpineK8s:
      tag: 1.18.2
      hash: sha256:768491682ca99e14498ddb62973a95a664a0525ca18e7ad0eaab2621d3124f5b
