apiVersion: v2
name: hermes-stack
description: Deploys a Hermesnode stack with options to enable or disable some services
type: application
version: 0.1.0

appVersion: 0.1.0

dependencies:
  - name: hermes-gateway
    repository: file://../dependency_charts/hermes_gateway
    version: 0.1.0
    condition: hermes-gateway.enabled

  - name: hermesnode
    repository: file://../dependency_charts/hermes
    version: 0.1.0
    condition: hermesnode.enabled

  - name: narada
    repository: file://../dependency_charts/narada
    version: 0.1.0
    condition: narada.enabled

  - name: narada-eddsa
    repository: file://../dependency_charts/narada-eddsa
    version: 0.1.0
    condition: narada-eddsa.enabled

  - name: dojima-chain
    repository: file://../dependency_charts/dojima-chain
    version: 0.1.0
    condition: dojima-chain.enabled