apiVersion: v2
name: hermes-stack
description: Deploys a Hermesnode stack with options to enable or disable some services
type: application
version: 0.1.0

appVersion: 0.1.0

dependencies:
  - name: hermes-gateway
    repository: file://../dependency_charts/hermes_gateway
    version: 0.1.0
    condition: hermes-gateway.enabled

  - name: hermesnode
    repository: file://../dependency_charts/hermes
    version: 0.1.0
    condition: hermesnode.enabled

  - name: narada
    repository: file://../dependency_charts/narada
    version: 0.1.0
    condition: narada.enabled

  - name: dojima-chain
    repository: file://../dependency_charts/dojima-chain
    version: 0.1.0
    condition: dojima-chain.enabled

  - name: binance-daemon
    repository: file://../dependency_charts/binance-daemon
    version: 0.1.0
    condition: binance-daemon.enabled

  - name: arweave-daemon
    repository: file://../dependency_charts/arweave-daemon
    version: 0.1.0
    condition: arweave-daemon.enabled

  - name: bitcoin-daemon
    repository: file://../dependency_charts/bitcoin-daemon
    version: 0.1.0
    condition: bitcoin-daemon.enabled

  - name: ethereum-daemon
    repository: file://../dependency_charts/ethereum-daemon
    version: 0.1.0
    condition: ethereum-daemon.enabled

  - name: gaia-daemon
    repository: file://../dependency_charts/gaia-daemon
    version: 0.1.0
    condition: gaia-daemon.enabled

  - name: polkadot-daemon
    repository: file://../dependency_charts/polkadot-daemon
    version: 0.1.0
    condition: polkadot-daemon.enabled

  - name: solana-daemon
    repository: file://../dependency_charts/solana-daemon
    version: 0.1.0
    condition: solana-daemon.enabled

  - name: bex-faucet
    repository: file://../dependency_charts/bex-faucet
    version: 0.1.0
    condition: bex-faucet.enabled

  - name: bex-hermes
    repository: file://../dependency_charts/bex-hermes
    version: 0.1.0
    condition: bex-hermes.enabled

  - name: bex-fiber
    version: 0.1.0
    condition: bex-fiber.enabled
    repository: file://../dependency_charts/bex-fiber

  - name: bex-single-msg
    version: 0.1.0
    condition: bex-single-msg.enabled
    repository: file://../dependency_charts/bex-single-msg