# Default values for narada.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

net: testnet
replicaCount: 1
type: validator
enodes: enode://f37759d2f892d068329f5cc8be1e2bdea70f453845b0aeaa6e514b9b9e8f2bf2667570e486afad2db54d48edc37489787dae518489e2441c6820452c34fde072@10.2.192.75:30303
unlock_address: 0xb9cA97199b0Dd85A48387B00Fd91d4195D1D2746
strategyType: Recreate

image:
  repository: asia-south1-docker.pkg.dev/prod-dojima/testnet/dojimachain
  pullPolicy: IfNotPresent
  tag: "a589faeb3_03-01-24"
  hash: "c9d1d7ec439bb726400bf79f5dd67eaf19f32361b01a582eebfcd5558c18b346"

chain_home_folder: "/root/.hermesnode"
signer:
  name: hermeschain
  password: password
  mnemonicSecret: ""
  passwordSecret: ""

environment:
  DOJIMA_RPC_URL: http://hermesnode:1317
  DOJIMA_GRPC_URL: hermesnode:9090

chainID:
  testnet: "hermes-testnet-v2"

env:
  faucet_dest: 0x265e016835494F05170E460Dad7a9380Bd3a1BFf
  faucet_amt: 1000000000
  eth_acc_pass: 0x265e016835494F05170E460Dad7a9380Bd3a1BFf

h4s:
  hermesApi: hermesnode:1317
  narada: http://narada:6040
  grpc: hermesnode:9090
  eth: http://ethereum-daemon.hermes-devnet:9545

hermes:
  testnet:
    image: asia-south1-docker.pkg.dev/prod-dojima/testnet/hermes
    tag: 9c6fad06_07-01-24
    hash: 5f39c49f2ec4a03147da06b56b4e730485b90f03ff46ec75dff89bdbacae4736

cmd_args:
  dojima_testnet_enable: true
  unlock_addr: 0xd526d5f47f863eff32b99bc4F9e77ddB4bd2929b
  password_path: /root/password.txt


imagePullSecrets: []
nameOverride: "dojima-chain"
fullnameOverride: "fdojima-chain"

persistence:
  enabled: true
  name: dojima-devnet-genesis
  size:
    testnet: 50Gi
    mainnet: 50Gi
    stagenet: 10Gi
#    mocknet: 10Gi
  accessMode: ReadWriteOnce
  # existingClaim: your-pvc
#  storageClass: gp3
  # hostPath: /host-path

service:
  type: ClusterIP
  port:
      wss: 8546
      http: 8545
      graphql: 8547
      devp2p: 30303

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "serv-dojima-chain"

priorityClassName: ""

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# service:
#   type: ClusterIP
#   port: 80

resources:
  requests:
    cpu: 4
    memory: 4Gi
  limits:
    memory: 4Gi

nodeSelector: {}

tolerations: []

affinity: {}

global:
  gateway:
    enabled: false
  images:
    alpineK8s:
      tag: 1.18.2
      hash: 768491682ca99e14498ddb62973a95a664a0525ca18e7ad0eaab2621d3124f5b
    busybox:
      tag: latest
      hash: caa382c432891547782ce7140fb3b7304613d3b0438834dce1cad68896ab110a