# Default values for narada.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

net: stagenet
replicaCount: 1

enable:
  node: "validator"
  http: true
  ws: true
  pprof: true


config:
  port: 30303
  http_addr: 0.0.0.0
  http_port: 8545
  http_api: eth,net,web3,txpool,dojimachain
  unlock: 0x0aAc3A39eBebA0D08E5A600D079e71bED430712F
  password: /root/password.txt
  pprof.address: 0.0.0.0
  pprof.port: 7071
  bootnodes: enode://bca13451e95a9105ed9e9099e44b3e76e0933347ba3d56619a42639265a1853a3cc882b5e7c1a5f2af417b3566ec40b571b10c9e6dda333dd3179de175c8f434@4.213.194.232:30303,enode://9ef64e51197fcd49ee8a3928137cd4ebff0538ebd876445201aef16f277c2a2b976ecf704be2c78af3adebb376bae58827a494c834fcbe6cfc2f3ccba8ae17d9@4.213.195.140:30303,enode://e0b704d798d2be30f42e47f9378ae76af075bec638fcec31b575127be339b33998d501efc6fd1e3ff439c0393297b20717f3af825782272bc00d4f602ff0c80e@4.213.200.84:30303
  cmd: false # enable to pass dojima-mainnet, dojima-testnet via command line


strategyType: Recreate

image:
  repository: asia-south1-docker.pkg.dev/prod-dojima/stagenet/dojimachain
  pullPolicy: IfNotPresent
  tag: "63eb20a59_3.5.6"
  hash: ""

chain_home_folder: "/root/.hermesnode"
doj_chf: "/root/.dojimachain"
signer:
  name: hermeschain
  password: ""
  mnemonicSecret: ""
  passwordSecret: ""

environment:
  DOJIMA_RPC_URL: http://hermesnode:1317
  DOJIMA_GRPC_URL: hermesnode:9090

chainID:
  testnet: "hermeschain-stagenet"

env:
  faucet_dest: 0x265e016835494F05170E460Dad7a9380Bd3a1BFf
  faucet_amt: 1000000000
  eth_acc_pass: 0x265e016835494F05170E460Dad7a9380Bd3a1BFf

h4s:
  hermesApi: hermesnode:1317
  narada: http://narada:6040
  grpc: hermesnode:9090
  rpc: http://hermesnode:26657
  hermes_rpc: http://4.213.194.232:26657
  eth: http://4.213.194.232:8545
  removeWait: true

hermes:
  testnet:
    image: asia-south1-docker.pkg.dev/prod-dojima/stagenet/hermes
    tag: 224232df_5.4.21
    hash: af37838a6800e4e866c4e42e2aace980ccdd6861bd983eb94dfc015a15f8ed39

cmd_args:
  dojima_testnet_enable: false
  unlock_addr: 0xd526d5f47f863eff32b99bc4F9e77ddB4bd2929b
  password_path: /root/password.txt


imagePullSecrets: []
nameOverride: "dojima-chain"
fullnameOverride: "dojima-chain"

persistence:
  enabled: true
  name: dojima-stagenet-genesis
  size:
    testnet: 50Gi
    mainnet: 50Gi
    stagenet: 10Gi
#    mocknet: 10Gi
  accessMode: ReadWriteOnce
  # existingClaim: your-pvc
#  storageClass: gp3
  # hostPath: /host-path

service:
  type: ClusterIP
  http: true
  ws: false
  port:
      wss: 8546
      http: 8545
      graphql: 8547
      devp2p: 30303
      authrpc: 8551

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "serv-dojima-chain"

priorityClassName: ""

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# service:
#   type: ClusterIP
#   port: 80

resources:
  requests:
    cpu: 4
    memory: 4Gi
  limits:
    cpu: 4
    memory: 4Gi

nodeSelector: {}

tolerations: []

affinity: {}

global:
  gateway:
    enabled: false
  images:
    alpineK8s:
      tag: 1.18.2
      hash: 768491682ca99e14498ddb62973a95a664a0525ca18e7ad0eaab2621d3124f5b
    busybox:
      tag: latest
      hash: caa382c432891547782ce7140fb3b7304613d3b0438834dce1cad68896ab110a