# Default values for narada.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

net: stagenet
replicaCount: 1

enable:
  node: "validator"
  http: true
  ws: false
  pprof: true


config:
  port: 30303
  http_addr: 0.0.0.0
  http_port: 8545
  http_api: eth,net,web3,txpool,dojimachain
  unlock: 0xa46C5EEa8F2C5691B754dc128b5364D13752979D
  password: /root/password.txt
  pprof.address: 0.0.0.0
  pprof.port: 7071
  bootnodes:


strategyType: Recreate

image:
  repository: asia-south1-docker.pkg.dev/prod-dojima/testnet/dojimachain
  pullPolicy: IfNotPresent
  tag: "4d617e0a0_v0.0.26"
  hash: "5c17a55e253cedac78cc2a8889a0d658cb1d84d3748a5afe178a67a193d251e4"

chain_home_folder: "/root/.hermesnode"
doj_chf: "/root/.dojimachain"
signer:
  name: hermeschain
  password: password
  mnemonicSecret: ""
  passwordSecret: ""

environment:
  DOJIMA_RPC_URL: http://hermesnode:1317
  DOJIMA_GRPC_URL: hermesnode:9090

chainID:
  testnet: "hermeschain-stagenet"

env:
  faucet_dest: 0x265e016835494F05170E460Dad7a9380Bd3a1BFf
  faucet_amt: 1000000000
  eth_acc_pass: 0x265e016835494F05170E460Dad7a9380Bd3a1BFf

h4s:
  hermesApi: hermesnode:1317
  narada: http://narada:6040
  grpc: hermesnode:9090
  eth: http://ethereum-daemon.hermes-stagenet:9545

hermes:
  testnet:
    image: asia-south1-docker.pkg.dev/prod-dojima/stagenet/hermes
    tag: 76910312_3.0.2
    hash: af37838a6800e4e866c4e42e2aace980ccdd6861bd983eb94dfc015a15f8ed39

cmd_args:
  dojima_testnet_enable: false
  unlock_addr: 0xd526d5f47f863eff32b99bc4F9e77ddB4bd2929b
  password_path: /root/password.txt


imagePullSecrets: []
nameOverride: "dojima-chain"
fullnameOverride: "dojima-chain"

persistence:
  enabled: true
  name: dojima-stagenet-genesis
  size:
    testnet: 50Gi
    mainnet: 1Ti
    stagenet: 10Gi
#    mocknet: 10Gi
  accessMode: ReadWriteOnce
  # existingClaim: your-pvc
#  storageClass: gp3
  # hostPath: /host-path

service:
  type: ClusterIP
  http: true
  ws: false
  port:
      wss: 8546
      http: 8545
      graphql: 8547
      devp2p: 30303
      authrpc: 8551

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "serv-dojima-chain"

priorityClassName: ""

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# service:
#   type: ClusterIP
#   port: 80

resources:
  requests:
    cpu: 4
    memory: 4Gi
  limits:
    memory: 4Gi

nodeSelector: {}

tolerations: []

affinity: {}

global:
  gateway:
    enabled: false
  images:
    alpineK8s:
      tag: 1.18.2
      hash: 768491682ca99e14498ddb62973a95a664a0525ca18e7ad0eaab2621d3124f5b
    busybox:
      tag: latest
      hash: caa382c432891547782ce7140fb3b7304613d3b0438834dce1cad68896ab110a