# Default values for narada.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

net: testnet
data_dir: single_node_testnet
replicaCount: 1

strategyType: Recreate

image:
  repository: 576263512135.dkr.ecr.ap-south-1.amazonaws.com/dojimanetwork/dojimachain
  pullPolicy: IfNotPresent
  tag: "testnet-0.1.0-2023-03-17"
  hash: "3f63f9ebc512e4a58834ec8a32088a36df9502d50cc7ac30d89e46107a8a0aca" # Not used for mocknet/testnet

chain_home_folder: "/root/.hermesnode"
signer:
  name: hermeschain
  password: password
  mnemonicSecret: "password"
  passwordSecret: "password"
  #genesis phrase
  signer_seed_phrase: "wink umbrella toss bleak patient extend palm asthma divorce quit track planet depend tenant mimic shiver girl segment lend unit body account monster lizard"
  # validator 1 phrase
  # signer_seed_phrase: "pipe expire lecture state pilot latin stamp senior market much dilemma tooth airport oblige flower caught risk canoe radar gadget tag narrow inch trust"

chainID:
  testnet: "hermes-testnet"

env:
  faucet_dest: 0x265e016835494F05170E460Dad7a9380Bd3a1BFf
  faucet_amt: 1000000000
  eth_acc_pass: 0x265e016835494F05170E460Dad7a9380Bd3a1BFf

h4s:
  hermesApi: fhermesnode-hermes:1317
  narada: http://narada:6040
  grpc: fhermesnode-hermes:9090
  eth: http://ethereum-daemon:9545

hermes:
  testnet:
    image: 576263512135.dkr.ecr.ap-south-1.amazonaws.com/hermes/hermes-node
    tag: testnet-1.89.0_59
    hash: 904f8c6e368697039f1473e934cf7517112e6e89bdd0d558cceb5f39f7e40c52

cmd_args:
  dojima_testnet_enable: true
  unlock_addr: 0xd526d5f47f863eff32b99bc4F9e77ddB4bd2929b
  password_path: /root/password.txt


imagePullSecrets: []
nameOverride: "dojima-chain"
fullnameOverride: "fdojima-chain"

persistence:
  enabled: true
  size:
    testnet: 5000Gi
#    mainnet: 50Gi
#    stagenet: 10Gi
#    mocknet: 10Gi
  accessMode: ReadWriteOnce
  # existingClaim: your-pvc
  # storageClass: "-"
  # hostPath: /host-path

service:
  type: ClusterIP
  port:
    testnet:
      wss: 8546
      http: 8545
      graphql: 8547
      devp2p: 30303

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "serv-dojima-chain"

priorityClassName: ""

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# service:
#   type: ClusterIP
#   port: 80

resources:
  requests:
    cpu: 2
    memory: 2Gi
  limits:
    cpu: 2
    memory: 4Gi

nodeSelector: {}

tolerations: []

affinity: {}

global:
  gateway:
    enabled: false
  images:
    alpineK8s:
      tag: 1.18.2
      hash: 768491682ca99e14498ddb62973a95a664a0525ca18e7ad0eaab2621d3124f5b
    busybox:
      tag: latest
      hash: caa382c432891547782ce7140fb3b7304613d3b0438834dce1cad68896ab110a