# Default values for narada.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

net: stagenet
replicaCount: 1

enable:
  node: "validator"
  http: true
  ws: true
  pprof: true


config:
  port: 30303
  http_addr: 0.0.0.0
  http_port: 8545
  http_api: personal,db,eth,net,web3,txpool,miner,admin,dojimachain
  unlock: 0x0aAc3A39eBebA0D08E5A600D079e71bED430712F
  password: /root/password.txt
  pprof.address: 0.0.0.0
  pprof.port: 7071
  bootnodes: enode://ec1aa3e88513cd7f779579594307d240c95b7fa18bfd81ffab39e19b7333a6769862a35e2f49ba49813b782faf2bd6f78895130e2c66dc9720e34a43f39e2bdd@34.93.45.195:30303,enode://175808486b39883ccc503e96bb53707085ee05d68fd7bc7fcfa071482c0319688d7d8519b5acad36f1606f8179b3bff8ff1bb2552820bfec53e22f78cf2ac60c@34.93.113.63:30303,enode://0173d8927dfb7884c21f74f6844e60f07013e79608441789443587262248c9bc0db6aad1e1308f472dd49aa88c4db107d9d6db944afd0390a2fb4d6e6f623883@4.188.3.254:30303
  cmd: false # enable to pass dojima-mainnet, dojima-testnet via command line


strategyType: Recreate

image:
  repository: asia-south1-docker.pkg.dev/prod-dojima/stagenet/dojimachain
  pullPolicy: IfNotPresent
  tag: "63eb20a59_3.5.6"
  hash: ""

chain_home_folder: "/root/.hermesnode"
doj_chf: "/root/.dojimachain"
signer:
  name: hermeschain
  password: ""
  mnemonicSecret: ""
  passwordSecret: ""

environment:
  DOJIMA_RPC_URL: http://hermesnode:1317
  DOJIMA_GRPC_URL: hermesnode:9090

chainID:
  testnet: "hermeschain-stagenet"

env:
  faucet_dest: 0x265e016835494F05170E460Dad7a9380Bd3a1BFf
  faucet_amt: 1000000000
  eth_acc_pass: 0x265e016835494F05170E460Dad7a9380Bd3a1BFf

h4s:
  hermesApi: hermesnode:1317
  narada: http://narada:6040
  grpc: hermesnode:9090
  rpc: http://hermesnode:26657
  hermes_rpc: http://34.93.45.195:26657
  eth: http://ethereum-daemon.hermes-stagenet:9545
  removeWait: true

hermes:
  testnet:
    image: asia-south1-docker.pkg.dev/prod-dojima/stagenet/hermes
    tag: 224232df_5.4.21
    hash: af37838a6800e4e866c4e42e2aace980ccdd6861bd983eb94dfc015a15f8ed39

cmd_args:
  dojima_testnet_enable: false
  unlock_addr: 0xd526d5f47f863eff32b99bc4F9e77ddB4bd2929b
  password_path: /root/password.txt


imagePullSecrets: []
nameOverride: "dojima-chain"
fullnameOverride: "dojima-chain"

persistence:
  enabled: true
  name: dojima-stagenet-genesis
  size:
    testnet: 50Gi
    mainnet: 1Ti
    stagenet: 100Gi
#    mocknet: 10Gi
  accessMode: ReadWriteOnce
  # existingClaim: your-pvc
#  storageClass: gp3
  # hostPath: /host-path

service:
  type: ClusterIP
  port:
      wss: 8546
      http: 8545
      graphql: 8547
      devp2p: 30303
      authrpc: 8551

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "serv-dojima-chain"

priorityClassName: ""

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# service:
#   type: ClusterIP
#   port: 80

resources:
  requests:
    cpu: 4
    memory: 4Gi
  limits:
    memory: 4Gi

nodeSelector: {}

tolerations: []

affinity: {}

global:
  gateway:
    enabled: false
  images:
    alpineK8s:
      tag: 1.18.2
      hash: 768491682ca99e14498ddb62973a95a664a0525ca18e7ad0eaab2621d3124f5b
    busybox:
      tag: latest
      hash: caa382c432891547782ce7140fb3b7304613d3b0438834dce1cad68896ab110a