# Default values for narada.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

net: stagenet
replicaCount: 1

enable:
  node: "validator"
  http: true
  ws: true
  pprof: true


config:
  port: 30303
  http_addr: 0.0.0.0
  http_port: 8545
  http_api: personal,db,eth,net,web3,txpool,miner,admin,dojimachain
  unlock: 0x0aAc3A39eBebA0D08E5A600D079e71bED430712F
  password: /root/password.txt
  pprof.address: 0.0.0.0
  pprof.port: 7071
  bootnodes: enode://c61ef5b86edffdcf227fb4fe9f28b1b9b1816eb2575e141e417b7ce06fb70b5baae293cbc6e61167d5b29f56b3707c34d7661306b7606f1f71b2048bc801bd9c@4.213.201.230:30303,enode://4745f6a0d8e36a0aa5593174d5effff6fd56814e01e780125658e33949c87cfac1c1d620afcddbd56a0099f5d65342850fd06482f820cd5492a7548014d7d2d6@4.213.41.144:30303,enode://767618fb3d4a8df2f4ffe13d99a0c379a5e48ea8242a940fdbe8d7528ebd368df06c7fdebbe10ea3ff96f8f974e192be320ed39347ada823b64781a308427367@20.235.223.219:30303,enode://2c0d38a8a394256b22210d4e0444aee234dda95e14d94629e594cb0665e95b36f4f15afe8d54593400fa0a1195a91a97bfb6b95b4a9f9bb8b2f078020422dab0@4.224.88.160:30303,enode://724a4832252c4b6656fc45c7ce8f15177478720f9c1db32c8aec1f9905d2d5d8beb2413742bde7adaf0f62dbcb77b1b10bd572ea0f295eda7bb0a4f3b2456b9b@4.213.206.217:30303
  cmd: false # enable to pass dojima-mainnet, dojima-testnet via command line


strategyType: Recreate

image:
  repository: asia-south1-docker.pkg.dev/prod-dojima/stagenet/dojimachain
  pullPolicy: IfNotPresent
  tag: "63eb20a59_3.5.6"
  hash: ""

chain_home_folder: "/root/.hermesnode"
doj_chf: "/root/.dojimachain"
signer:
  name: hermeschain
  password: ""
  mnemonicSecret: ""
  passwordSecret: ""

environment:
  DOJIMA_RPC_URL: http://hermesnode:1317
  DOJIMA_GRPC_URL: hermesnode:9090

chainID:
  testnet: "hermeschain-stagenet"

env:
  faucet_dest: 0x265e016835494F05170E460Dad7a9380Bd3a1BFf
  faucet_amt: 1000000000
  eth_acc_pass: 0x265e016835494F05170E460Dad7a9380Bd3a1BFf

h4s:
  hermesApi: hermesnode:1317
  narada: http://narada:6040
  grpc: hermesnode:9090
  rpc: http://hermesnode:26657
  hermes_rpc: http://4.213.201.230:26657
  eth: http://ethereum-daemon.hermes-stagenet:9545
  removeWait: true

hermes:
  testnet:
    image: asia-south1-docker.pkg.dev/prod-dojima/stagenet/hermes
    tag: 224232df_5.4.21
    hash: af37838a6800e4e866c4e42e2aace980ccdd6861bd983eb94dfc015a15f8ed39

cmd_args:
  dojima_testnet_enable: false
  unlock_addr: 0xd526d5f47f863eff32b99bc4F9e77ddB4bd2929b
  password_path: /root/password.txt


imagePullSecrets: []
nameOverride: "dojima-chain"
fullnameOverride: "dojima-chain"

persistence:
  enabled: true
  name: dojima-stagenet-genesis
  size:
    testnet: 50Gi
    mainnet: 50Gi
    stagenet: 10Gi
#    mocknet: 10Gi
  accessMode: ReadWriteOnce
  # existingClaim: your-pvc
#  storageClass: gp3
  # hostPath: /host-path

service:
  type: ClusterIP
  http: true
  ws: false
  port:
      wss: 8546
      http: 8545
      graphql: 8547
      devp2p: 30303
      authrpc: 8551

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "serv-dojima-chain"

priorityClassName: ""

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# service:
#   type: ClusterIP
#   port: 80

resources:
  requests:
    cpu: 100m
    memory: 1Gi
  limits:
    cpu: 200m
    memory: 2Gi

nodeSelector: {}

tolerations: []

affinity: {}

global:
  gateway:
    enabled: false
  images:
    alpineK8s:
      tag: 1.18.2
      hash: 768491682ca99e14498ddb62973a95a664a0525ca18e7ad0eaab2621d3124f5b
    busybox:
      tag: latest
      hash: caa382c432891547782ce7140fb3b7304613d3b0438834dce1cad68896ab110a