# Default values for narada.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

net: testnet
data_dir: single_node_testnet
replicaCount: 1

strategyType: Recreate

image:
  repository: asia-south1-docker.pkg.dev/prod-dojima/testnet/dojimachain
  pullPolicy: IfNotPresent
  tag: "testnet-23-11-23"
  hash: "cad3975a2ece8b7d08477aaf80a20098ad409fd197145145177cc22c9ad838a0" # Not used for mocknet/testnet

chain_home_folder: "/root/.hermesnode"
signer:
  name: hermeschain
  password: password
  mnemonicSecret: ""
  passwordSecret: ""

chainID:
  testnet: "hermes-testnet-v2"

env:
  faucet_dest: 0x265e016835494F05170E460Dad7a9380Bd3a1BFf
  faucet_amt: 1000000000
  eth_acc_pass: 0x265e016835494F05170E460Dad7a9380Bd3a1BFf

h4s:
  hermesApi: hermesnode:1317
  narada: http://narada:6040
  grpc: hermesnode:9090
  eth: http://ethereum-daemon:9545

hermes:
  testnet:
    image: asia-south1-docker.pkg.dev/prod-dojima/testnet/hermes
    tag: 3dcb6a5a_30-12-23
    hash: 1a6a992dc6dcc5cee01c2541a6fc8a2ee10fccfbc2b085fa865efa2a9e8be7a2

cmd_args:
  dojima_testnet_enable: true
  unlock_addr: 0xd526d5f47f863eff32b99bc4F9e77ddB4bd2929b
  password_path: /root/password.txt


imagePullSecrets: []
nameOverride: "dojima-chain"
fullnameOverride: "fdojima-chain"

persistence:
  enabled: true
  size:
    testnet: 50Gi
#    mainnet: 50Gi
#    stagenet: 10Gi
#    mocknet: 10Gi
  accessMode: ReadWriteOnce
  # existingClaim: your-pvc
  storageClass: gp3
  # hostPath: /host-path

service:
  type: ClusterIP
  port:
    testnet:
      wss: 8546
      http: 8545
      graphql: 8547
      devp2p: 30303

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "serv-dojima-chain"

priorityClassName: ""

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# service:
#   type: ClusterIP
#   port: 80

resources:
  requests:
    cpu: 4
    memory: 4Gi
  limits:
    memory: 8Gi

nodeSelector: {}

tolerations: []

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.kubernetes.io/zone
              operator: In
              values:
                - asia-south1-c

global:
  gateway:
    enabled: false
  images:
    alpineK8s:
      tag: 1.18.2
      hash: 768491682ca99e14498ddb62973a95a664a0525ca18e7ad0eaab2621d3124f5b
    busybox:
      tag: latest
      hash: caa382c432891547782ce7140fb3b7304613d3b0438834dce1cad68896ab110a