# Default values for ethereum-daemon.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

net: testnet

replicaCount: 1

image:
  blockscout:
    repository: 576263512135.dkr.ecr.ap-south-1.amazonaws.com/dojima-blockscout
    pullPolicy: IfNotPresent
    tag: "testnet-0.1.0-2023-02-03"
    hash: "sha256:9114616bf6356f3af067e8aabfdaa5ee533e61f949aee9bef4ebc50d9a700c61"
  smartcontract_verifier:
    repository: ghcr.io/blockscout/smart-contract-verifier
    tag: main
  postgres:
    image: postgres:13.4

# You need to provide some config file. For example, just copy `example_config.toml`
config: "config.toml"

env:
  pg_pass: ""
  pg_user: postgres
  pg_host_auth_method: 'trust'
  pg_db_name: postgres
  eth_json_var: geth
  coin: DOJ
  chain_id: 1001
  eth_json_http: http://dojima-chain.hermes-testnet:8545
  eth_ws_url: ws://dojima-chain.hermes-testnet:8545/ws
  eth_jsonrpc_transport: http
  database_url: "postgresql://postgres:@localhost:5432/postgres?ssl=false"
  secret_key: YUt2Iifi/4q7envZCRZZhyCcfgmcfGr26/Uk6Jkc/YCXPNJIORS0Wb1DaejWKaeC
  mix_env: dev
  ecto_use_ssl: false
  trace_first_block: 221443
  indexer_dis_pending_fetcher: true
  indexer_dis_internal_tx_fetcher: true
  indexer_dis_block_rew_fetcher: true
  indexer_empty_blocks_sanitize: 1000
  network: "(Dojima Network)"
  sub_network: "Dojima chain"
  coin_name: DOJ
  cache_tx_count_period: 7200
  cache_block_count_period: 7200
  pool_size: 120
  pool_size_api: 400
  link_other_bex: true
  other_explorers: "{ 'Hermes': 'https://bex-test.h4s.dojima.network' }"
  show_price_chart: true
  show_txs_chart: true
  history_fetch_interval: 240
  txs_stats_days_to_compile_at_init: 10
  coin_balance_history_days: 90
  apps_menu: true
  display_token_icons: true
  api_rate_limit: 100
  api_rate_limit_by_key: 30
  api_rate_limit_by_ip: 30
  indexer_memory_limit: 7
  enable_tx_stats: true
  disable_exchange_rate: true
  logo: /images/doj.svg
  logo_footer: /images/doj.svg
  api_url: https://doj-bex-test.dojima.network
  blockscout_host: doj-bex-test.dojima.network
  enable_rs_verify_service: true
  rs_verify_url: http://localhost:8043

imagePullSecrets: []
nameOverride: "dojima-blockscoutd"
fullnameOverride: "fdojima-blockscoutd"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "serv-dojima-blockscout"

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  postgres: 5432
  bs: 4000
  bs_rs: 8043

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # cert-manager.io/cluster-issuer: letsencrypt-production
  hosts: []
    # - host: midgard.example.com
    #   paths:
    #   - path: /
    #     backend:
    #       serviceName: gateway
    #       servicePort: midgard
  tls: []
    # - secretName: midgard-tls
    #   hosts:
    #     - midgard.example.com

persistence:
  enabled: true
  size:
    testnet: 100Gi
    stagenet: 150Gi
    mainnet: 200Gi
  accessMode: ReadWriteOnce
  # storageClass: "-"
  #
resources:
  limits:
    # cpu: 1
    memory: 18Gi
  requests:
    cpu: 4
    memory: 8Gi

nodeSelector: {}

tolerations: []

affinity: {}

# necessary for lint
global:
  images:
    alpine:
      tag: foo
      hash: bar
