# Default values for ethereum-daemon.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

net: testnet

replicaCount: 1

image:
  blockscout:
    repository: 576263512135.dkr.ecr.ap-south-1.amazonaws.com/dojima-blockscout
    pullPolicy: IfNotPresent
    tag: "testnet-0.1.0-2022-12-30"
    hash: "sha256:110c11ebda6d422aa9466db7f25b31b2cd51638cfc3b92823fc3bb20f257bace"
  postgres:
    image: postgres:14

env:
  pg_pass: ""
  pg_user: postgres
  pg_host_auth_method: 'trust'
  eth_json_var: geth
  coin: DOJ
  chain_id: 1001
  eth_json_http: http://dojima-chain.hermesnode-test:8545
  database_url: "postgresql://postgres:@localhost:5432/postgres?ssl=false"
  secret_key: YUt2Iifi/4q7envZCRZZhyCcfgmcfGr26/Uk6Jkc/YCXPNJIORS0Wb1DaejWKaeC
  mix_env: dev
  ecto_use_ssl: false
  trace_first_block: 221443

imagePullSecrets: []
nameOverride: "dojima-blockscoutd"
fullnameOverride: "fdojima-blockscoutd"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "serv-dojima-blockscout"

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 5432

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # cert-manager.io/cluster-issuer: letsencrypt-production
  hosts: []
    # - host: midgard.example.com
    #   paths:
    #   - path: /
    #     backend:
    #       serviceName: gateway
    #       servicePort: midgard
  tls: []
    # - secretName: midgard-tls
    #   hosts:
    #     - midgard.example.com

persistence:
  enabled: true
  size:
    testnet: 100Gi
    stagenet: 150Gi
    mainnet: 200Gi
  accessMode: ReadWriteOnce
  # storageClass: "-"
  #
resources:
  limits:
    # cpu: 1
    memory: 6Gi
  requests:
    cpu: 2
    memory: 4Gi

nodeSelector: {}

tolerations: []

affinity: {}

# necessary for lint
global:
  images:
    alpine:
      tag: foo
      hash: bar
