# Default values for binance-daemon.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

net: testnet

replicaCount: 1

image:
  name: asia.gcr.io/prod-dojima/hermes
  tag: "testnet-1.89.0_62"
  hash: "904f8c6e368697039f1473e934cf7517112e6e89bdd0d558cceb5f39f7e40c52"
  testnet: "textury/arlocal:latest"

imagePullSecrets: []
nameOverride: "hello-word"
fullnameOverride: "fhello-wordd"

recoverNineRealmsSnapshot: false
hermesApi: hermesnode:1318
service:
  type: ClusterIP
  port:
    testnet:
      p2p: 26656
      rpc: 26657
      api: 1984
    stagenet:
      p2p: 27146
      rpc: 27147
    mainnet:
      p2p: 27146
      rpc: 27147

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # cert-manager.io/cluster-issuer: letsencrypt-production
  hosts: []
    # - host: midgard.example.com
    #   paths:
    #   - path: /
    #     backend:
    #       serviceName: gateway
    #       servicePort: midgard
  tls: []
    # - secretName: midgard-tls
    #   hosts:
    #     - midgard.example.com

persistence:
  enabled: true
  size:
    testnet: 200Gi
    stagenet: 300Gi
    mainnet: 300Gi
  accessMode: ReadWriteOnce
  storageClass: gp3

storageclass:
  name: hello-word

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "serv-hello-word"

podSecurityContext:
  fsGroup: 1000

securityContext: {}

resources:
  requests:
    cpu: 0.1
    memory: 4000Mi
  limits:
    cpu: 0.5
    memory: 7500Mi

nodeSelector: {}

tolerations: []

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.kubernetes.io/zone
              operator: In
              values:
                - asia-south1-c


global:
  tag:
  net: testnet
  peer:
  passwordSecret:
  mnemonicSecret:
  gateway:
    enabled: false
    name: "hermesnode-gateway"
  images:
    alpineK8s:
      tag: 1.18.2
      hash: 768491682ca99e14498ddb62973a95a664a0525ca18e7ad0eaab2621d3124f5b
    busybox:
      tag: latest
      hash: caa382c432891547782ce7140fb3b7304613d3b0438834dce1cad68896ab110a

