{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "narada-eddsa.serviceAccountName" . }}
  labels:
{{ include "narada-eddsa.labels" . | nindent 4 }}
{{- end -}}
