apiVersion: v1
kind: Service
metadata:
  name: {{ include "narada-eddsa.fullname" . }}
  labels:
    {{- include "narada-eddsa.labels" . | nindent 4 }}
  annotations:
    # AWS
    #service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
   # service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    #service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    #service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: {{ .Values.service.type }}
  {{- if ne "ClusterIP" .Values.service.type }}
  externalTrafficPolicy: Local
  {{- end }}
  ports:
    - port: {{ .Values.service.port.tss_p2p }}
      targetPort: tss-p2p
      protocol: TCP
      name: tss-p2p
    - port: {{ .Values.service.port.p2p_id }}
      targetPort: p2p-id
      protocol: TCP
      name: p2p-id
    - name: prometheus
      port: {{ .Values.service.port.prometheus}}
      targetPort: prometheus
      protocol: TCP
    - name: eddsa-http
      port: {{ include "narada-eddsa-nqs.port" . }}
      targetPort: eddsa-http
      protocol: TCP
  selector:
    {{- include "narada-eddsa.selectorLabels" . | nindent 4 }}
