# Default values for binance-daemon.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

net: mocknet
chain:
  testnet: westend
  mainnet: polkadot

replicaCount: 1

image:
  name: 576263512135.dkr.ecr.ap-south-1.amazonaws.com/narada-ci
  tag: "polkadot-daemon-0.1.0"
  hash: "c3902fc7008ec884c396404919838840a3e4b24b81ece5f0524450ebf0f6c2dd"
  testnet: "parity/polkadot:v0.9.32"

imagePullSecrets: []
nameOverride: "narada-polkadotd"
fullnameOverride: "fnarada-polkadotd"

recoverNineRealmsSnapshot: false

service:
  type: ClusterIP
  port:
    testnet:
      p2p: 30333
      http: 9933
      ws: 9944
    stagenet:
      p2p: 30333
      http: 9933
      ws: 9944
    mainnet:
      p2p: 30333
      http: 9933
      ws: 9944

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # cert-manager.io/cluster-issuer: letsencrypt-production
  hosts: []
    # - host: midgard.example.com
    #   paths:
    #   - path: /
    #     backend:
    #       serviceName: gateway
    #       servicePort: midgard
  tls: []
    # - secretName: midgard-tls
    #   hosts:
    #     - midgard.example.com

persistence:
  enabled: true
  size:
    testnet: 50Gi
    stagenet: 500Gi
    mainnet: 500Gi
  accessMode: ReadWriteOnce
  # storageClass: "-"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "serv-narada-polakdot"

podSecurityContext:
  fsGroup: 1000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  requests:
    cpu: 2
    memory: 6Gi
  limits:
    # cpu: 2
    memory: 6Gi

nodeSelector: {}

tolerations: []

affinity: {}


global:
  tag:
  net: testnet
  peer:
  passwordSecret:
  mnemonicSecret:
  gateway:
    enabled: false
    name: "hermesnode-gateway"
  images:
    alpineK8s:
      tag: 1.18.2
      hash: 768491682ca99e14498ddb62973a95a664a0525ca18e7ad0eaab2621d3124f5b
    busybox:
      tag: latest
      hash: caa382c432891547782ce7140fb3b7304613d3b0438834dce1cad68896ab110a

