apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "narada.fullname" . }}
  labels:
    {{- include "narada.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.strategyType }}
  selector:
    matchLabels:
      {{- include "narada.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "narada.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "narada.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}

      initContainers:
      - name: init-external-ip
        image: "alpine/k8s:{{ .Values.global.images.alpineK8s.tag }}@sha256:{{ .Values.global.images.alpineK8s.hash }}"
        {{- if .Values.global.gateway.enabled }}
        command: ['/scripts/external-ip.sh', 'false', '{{ .Values.global.gateway.name }}', '{{ include "narada.fullname" . }}-external-ip']
        {{- else }}
        command: ['/scripts/external-ip.sh', 'false', '{{ include "narada.fullname" . }}', '{{ include "narada.fullname" . }}-external-ip']
        {{- end }}
        volumeMounts:
        - name: scripts
          mountPath: /scripts
      - name: init-keepalive
        image: "busybox:{{ .Values.global.images.busybox.tag }}@sha256:{{ .Values.global.images.busybox.hash }}"
        command:
        - /bin/sh
        - -c
        - |
          sysctl -w net.ipv4.tcp_keepalive_time=120
          sysctl -w net.ipv4.tcp_keepalive_intvl=60
          sysctl -w net.ipv4.tcp_keepalive_probes=3
        securityContext:
          privileged: true
      - name: init-hermeschain
        image: "busybox:{{ .Values.global.images.busybox.tag }}@sha256:{{ .Values.global.images.busybox.hash }}"
        command: ['sh', '-c', 'until nc -zv {{ .Values.hermesApi }}; do echo waiting for hermesnode; sleep 2; done']
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "narada.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/scripts/narada.sh"]
          {{- if .Values.debug }}
          args: ["narada", "-c", "/etc/narada/config.json", "-l",  {{ .Values.narada_log_level }} ]
          {{- else }}
          args: ["narada", "-c", "/etc/narada/config.json"]
          {{- end }}
          volumeMounts:
            - mountPath: /var/data/narada
              name: data
              subPath: data
            - mountPath: /root/.hermes
              name: data
              subPath: hermesnode
            - mountPath: /etc/narada
              name: data
              subPath: etc
          env:
            - name: EXTERNAL_IP
              valueFrom:
                configMapKeyRef:
                  name: {{ include "narada.fullname" . }}-external-ip
                  key: externalIP
            - name: NET
              value: {{ include "narada.net" . }}
            - name: CHAIN_API
              value: {{ .Values.hermesApi }}
            - name: CHAIN_RPC
              value: {{ include "narada.hermesnodeDaemon" . }}
            - name: BINANCE_HOST
              value: {{ include "narada.binanceDaemon" . }}
            - name: BINANCE_START_BLOCK_HEIGHT
              value: "{{ .Values.binanceDaemon.binanceStartBlockHeight }}"
            - name: BTC_HOST
              value: {{ include "narada.bitcoinDaemon" . }}
            - name: BTC_START_BLOCK_HEIGHT
              value: "{{ .Values.bitcoinDaemon.bitcoinStartBlockHeight }}"
            - name: AR_HOST
              value: {{ include "narada.arweaveDaemon" . }}
            - name: AR_START_BLOCK_HEIGHT
              value: "{{ .Values.arweaveDaemon.arweaveStartBlockHeight }}"
            - name: DOT_HOST
              value: {{ include "narada.polkaDaemon" . }}
            - name: DOT_START_BLOCK_HEIGHT
              value: "{{ .Values.polkaDaemmon.polkaStartBlockHeight }}"
            - name: SOL_HOST
              value: {{ include "narada.solanaDaemon" . }}
            - name: SOL_HOST_WS
              value: {{ include "narada.solanaWsDaemon" . }}
            - name: SOL_START_BLOCK_HEIGHT
              value: "{{ .Values.solanaDaemon.solanaStartBlockHeight }}"
            - name: GAIA_HOST
              value: {{ include "narada.gaiaDaemon" . }}
            - name: GAIA_GRPC_HOST
              value: {{ include "narada.gaiaDaemonGRPC" . }}
            - name: GAIA_GRPC_TLS
              value: "{{ include "narada.gaiaDaemonGRPCTLS" . }}"
            - name: GAIA_START_BLOCK_HEIGHT
              value: "{{ .Values.gaiaDaemon.gaiaStartBlockHeight }}"
            - name: CHAIN_HOME_FOLDER
              value: {{ .Values.chain_home_folder }}
            {{- if not .Values.gaiaDaemon.enabled }}
            - name: GAIA_DISABLED
              value: "true"
            {{- end}}
            - name: ETH_HOST
              value: {{ include "narada.ethereumDaemon" . }}
            - name: ETH_START_BLOCK_HEIGHT
              value: "{{ .Values.ethereumDaemon.ethereumStartBlockHeight }}"
            - name: ETH_SUGGESTED_FEE_VERSION
              value: '{{ include "narada.ethSuggestedFeeVersion" . }}'
            - name: PEER
              value: {{ .Values.peer }}
            - name: SEED
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SIGNER_NAME
              value: {{ .Values.signer.name }}
            - name: SIGNER_PASSWD
              value: {{ .Values.signer.password }}
            - name: SIGNER_SEED_PHRASE
              value: {{ .Values.signer.signer_seed_phrase }}
            - name: CHAIN_ID
              value: {{ include "narada.chainID" . }}
            - name: AR_KEY_PATH
              value: "/scripts/testnet/arweave_testnet/2txTDSdb_RjG12uHZlVsB5jrfPzqxtzScKTtPef2KZ0.json"
            - name: AR_ADDRESS
              value: "2txTDSdb_RjG12uHZlVsB5jrfPzqxtzScKTtPef2KZ0"
            - name: SOL_KEYPATH
              value: "/scripts/testnet/solana_testnet/82iP5jLLyiuTHbQRrSwUgZ6sKycT2mjbNkncgpm7Duvg.json"
            - name: SOL_PUBKEY
              value: "82iP5jLLyiuTHbQRrSwUgZ6sKycT2mjbNkncgpm7Duvg"
            - name: DOT_ADDRESS
              value: "5H16DLfWFLdpm5C4f9Qr6UkADsT1PtD9jELWF9WKuiC7St1T"
            - name: DB_PATH
              value: /var/data
            - name: PREPARAM
              value: {{ .Values.preparam }}
            - name: INCLUDE_BINANCE_CHAIN
              value: {{ .Values.chains.include_binance_chain | quote }}
            - name: INCLUDE_BTC_CHAIN
              value: {{ .Values.chains.include_btc_chain | quote }}
            - name: INCLUDE_ETH_CHAIN
              value: "{{ .Values.chains.include_eth_chain }}"
            - name: INCLUDE_AR_CHAIN
              value: "{{ .Values.chains.include_ar_chain }}"
            - name: INCLUDE_DOT_CHAIN
              value: "{{ .Values.chains.include_dot_chain }}"
            - name: INCLUDE_SOL_CHAIN
              value: "{{ .Values.chains.include_sol_chain }}"
            - name: INCLUDE_GAIA_CHAIN
              value: "{{ .Values.chains.include_gaia_chain }}"
            - name: DOJIMA_CHAIN_ID
              value: "{{ .Values.dojima_chain.chain_id }}"
            - name: DOJIMA_RPC_URL
              value: "{{ .Values.dojima_chain.rpc_url }}"
            - name: DOJIMA_GRPC_URL
              value: "{{ .Values.dojima_chain.grpc_url }}"
          ports:
            - name: p2p
              containerPort: {{ .Values.service.port.p2p }}
              protocol: TCP
            - name: http
              containerPort: {{ .Values.service.port.http }}
              protocol: TCP
            - name: prometheus
              containerPort: {{ .Values.service.port.prometheus}}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      volumes:
      - name: data
      {{- if and .Values.persistence.enabled (not .Values.persistence.hostPath) }}
        persistentVolumeClaim:
          claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ template "narada.fullname" . }}{{- end }}
      {{- else if and .Values.persistence.enabled .Values.persistence.hostPath }}
        hostPath:
          path: {{ .Values.persistence.hostPath }}
          type: DirectoryOrCreate
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: scripts
        configMap:
          name: {{ include "narada.fullname" . }}-scripts
          defaultMode: 0777
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
