{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "narada.serviceAccountName" . }}
  labels:
{{ include "narada.labels" . | nindent 4 }}
{{- end -}}
