apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gateway.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "gateway.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      - name: init-external-ip
        image: "alpine/k8s:{{ .Values.global.images.alpineK8s.tag }}@sha256:{{ .Values.global.images.alpineK8s.hash }}"
        command: ['/scripts/external-ip.sh', 'false', '{{ include "gateway.fullname" . }}', '{{ include "gateway.fullname" . }}-external-ip']
        volumeMounts:
        - name: config
          mountPath: /scripts
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}@sha256:{{ .Values.image.hash }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
            name: config
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 8443
              protocol: TCP
            - name: narada-api
              containerPort: {{ .Values.service.port.narada.api }}
              protocol: TCP
            - name: narada-p2p
              containerPort: {{ .Values.service.port.narada.p2p }}
              protocol: TCP
            - name: bex-fiber
              containerPort: {{ include "gateway-bex-fiber.api" . }}
              protocol: TCP
            - name: api
              containerPort: {{ .Values.service.port.api }}
              protocol: TCP
            - name: rpc
              containerPort: {{ include "gateway.rpc" . }}
              protocol: TCP
            - name: p2p
              containerPort: {{ include "gateway.p2p" . }}
              protocol: TCP
            - name: arweave-api
              containerPort: {{ include "gateway-arweave-daemon.api" .}}
              protocol: TCP
            - name: solana-rpc
              containerPort: {{ include "gateway-solana-daemon.rpc" .}}
              protocol: TCP
            - name: solana-wss
              containerPort: {{ include "gateway-solana-daemon.wss" .}}
              protocol: TCP
            - name: solana-gossip
              containerPort: {{ include "gateway-solana-daemon.gossip" .}}
              protocol: TCP
            - name: solana-tpu
              containerPort: {{ include "gateway-solana-daemon.tpu" .}}
              protocol: TCP
            - name: solana-udp
              containerPort: {{ include "gateway-solana-daemon.udp" .}}
              protocol: UDP
            - name: polkadot-wss
              containerPort: {{ include "gateway-polkadot-daemon.wss" .}}
              protocol: TCP
            - name: polkadot-http
              containerPort: {{ include "gateway-polkadot-daemon.http" .}}
              protocol: TCP
            - name: dc-http
              containerPort: {{ include "gateway-dojima-chain.http" .}}
              protocol: TCP
            - name: dc-rpc
              containerPort: {{ include "gateway-dojima-chain.rpc" .}}
              protocol: TCP
            - name: faucet
              containerPort: {{ include "gateway-dojima-chain.faucet" .}}
              protocol: TCP
            - name: eth-api
              containerPort: {{ include "gateway-eth-chain.api" . }}
              protocol: TCP
            - name: eth-wss
              containerPort: {{ include "gateway-eth-chain.wss" . }}
              protocol: TCP
            - name: bnb-rpc
              containerPort: {{ include "gateway-bnb-chain.rpc" .}}
              protocol: TCP
            - name: hermes-grpc
              containerPort: {{ include "gateway-hermes.grpc" .}}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: https
          readinessProbe:
            httpGet:
              path: /healthz
              port: https
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: config
        configMap:
          name: {{ include "gateway.fullname" . }}
          defaultMode: 0777
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
