apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
  annotations:
    # AWS
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-south-1:576263512135:certificate/36a81c43-d2f2-4d33-8ff6-cbb564684ba3
    # Only run SSL on the port named "https" below.
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: hermes-grpc,solana-rpc,polkadot-wss,eth-api,dc-rpc,polkadot-http,https,dc-http,bnb-rpc,solana-wss,arweave-api
    # hcloud
    load-balancer.hetzner.cloud/location: nbg1
    load-balancer.hetzner.cloud/use-private-ip: "true"
    load-balancer.hetzner.cloud/disable-private-ingress: "true"
    load-balancer.hetzner.cloud/type: lb11
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: Local
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 443
      targetPort: http
      protocol: TCP
      name: https
    {{- if .Values.validator }}
    - port: {{ .Values.service.port.narada.api }}
      targetPort: narada-api
      protocol: TCP
      name: narada-api
    - port: {{ .Values.service.port.narada.p2p }}
      targetPort: narada-p2p
      protocol: TCP
      name: narada-p2p
    {{- end }}
    {{- if .Values.fiber }}
    - port: {{ .Values.service.port.fiber.testnet.api }}
      targetPort: bex-fiber
      protocol: TCP
      name: bex-fiber
    {{- end }}
    {{- if .Values.api }}
    - port: {{ .Values.service.port.api }}
      targetPort: api
      protocol: TCP
      name: api
    {{- end }}
    {{- if .Values.rpc.enabled }}
    - port: {{ include "gateway.rpc" . }}
      targetPort: rpc
      protocol: TCP
      name: rpc
    {{- end }}
    - port: {{ include "gateway.p2p" . }}
      targetPort: p2p
      protocol: TCP
      name: p2p
    {{- if .Values.arweave }}
    - port: {{ include "gateway-arweave-daemon.api" .}}
      targetPort: arweave-api
      protocol: TCP
      name: arweave-api
    {{- end }}
    {{- if .Values.solana }}
    - port: {{ include "gateway-solana-daemon.rpc" .}}
      targetPort: solana-rpc
      protocol: TCP
      name: solana-rpc
    - port: {{ include "gateway-solana-daemon.wss" .}}
      targetPort: solana-wss
      protocol: TCP
      name: solana-wss
    - port: {{ include "gateway-solana-daemon.gossip" .}}
      targetPort: solana-gossip
      protocol: TCP
      name: solana-gossip
    - port: {{ include "gateway-solana-daemon.tpu" .}}
      targetPort: solana-tpu
      protocol: TCP
      name: solana-tpu
    {{- end }}
    {{- if .Values.polkadot }}
    - port: {{ include "gateway-polkadot-daemon.http" .}}
      targetPort: polkadot-http
      protocol: TCP
      name: polkadot-http
    - port: {{ include "gateway-polkadot-daemon.wss" .}}
      targetPort: polkadot-wss
      protocol: TCP
      name: polkadot-wss
    {{- end }}
    {{- if .Values.dojima_chain }}
    - port: {{ include "gateway-dojima-chain.http" . }}
      targetPort: dc-http
      protocol: TCP
      name: dc-http
    - port: {{ include "gateway-dojima-chain.rpc" . }}
      targetPort: dc-rpc
      protocol: TCP
      name: dc-rpc
    {{- end }}
    {{- if .Values.faucet }}
    - port: {{ include "gateway-dojima-chain.faucet" . }}
      targetPort: faucet
      protocol: TCP
      name: faucet
    {{- end }}
    {{- if .Values.eth }}
    - port: {{ include "gateway-eth-chain.api" . }}
      targetPort: eth-api
      protocol: TCP
      name: eth-api
    - port: {{ include "gateway-eth-chain.wss" . }}
      targetPort: eth-wss
      protocol: TCP
      name: eth-wss
    {{- end }}
    {{- if .Values.binance }}
    - port: {{ include "gateway-bnb-chain.rpc" . }}
      targetPort: bnb-rpc
      protocol: TCP
      name: bnb-rpc
    {{- end }}
    {{- if .Values.grpc }}
    - port: {{ include "gateway-hermes.grpc" . }}
      targetPort: hermes-grpc
      protocol: TCP
      name: hermes-grpc
    {{- end }}
  selector:
    {{- include "gateway.selectorLabels" . | nindent 4 }}
