apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
  annotations:
    # AWS
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    # hcloud
    load-balancer.hetzner.cloud/location: nbg1
    load-balancer.hetzner.cloud/use-private-ip: "true"
    load-balancer.hetzner.cloud/disable-private-ingress: "true"
    load-balancer.hetzner.cloud/type: lb11
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: Local
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.validator }}
    - port: {{ .Values.service.port.narada.api }}
      targetPort: narada-api
      protocol: TCP
      name: narada-api
    - port: {{ .Values.service.port.narada.p2p }}
      targetPort: narada-p2p
      protocol: TCP
      name: narada-p2p
    {{- end }}
    {{- if .Values.midgard }}
    - port: {{ .Values.service.port.midgard }}
      targetPort: midgard
      protocol: TCP
      name: midgard
    {{- end }}
    {{- if .Values.api }}
    - port: {{ .Values.service.port.api }}
      targetPort: api
      protocol: TCP
      name: api
    {{- end }}
    {{- if .Values.rpc.enabled }}
    - port: {{ include "gateway.rpc" . }}
      targetPort: rpc
      protocol: TCP
      name: rpc
    {{- end }}
    - port: {{ include "gateway.p2p" . }}
      targetPort: p2p
      protocol: TCP
      name: p2p
    {{- if .Values.arweave }}
    - port: {{ include "gateway-arweave-daemon.api" .}}
      targetPort: arweave-api
      protocol: TCP
      name: arweave-api
    {{- end }}
    {{- if .Values.solana }}
    - port: {{ include "gateway-solana-daemon.rpc" .}}
      targetPort: solana-rpc
      protocol: TCP
      name: solana-rpc
    - port: {{ include "gateway-solana-daemon.wss" .}}
      targetPort: solana-wss
      protocol: TCP
      name: solana-wss
    - port: {{ include "gateway-solana-daemon.gossip" .}}
      targetPort: solana-gossip
      protocol: TCP
      name: solana-gossip
    - port: {{ include "gateway-solana-daemon.tpu" .}}
      targetPort: solana-tpu
      protocol: TCP
      name: solana-tpu
    {{- end }}
    {{- if .Values.polkadot }}
    - port: {{ include "gateway-polkadot-daemon.http" .}}
      targetPort: polkadot-http
      protocol: TCP
      name: polkadot-http
    - port: {{ include "gateway-polkadot-daemon.wss" .}}
      targetPort: polkadot-wss
      protocol: TCP
      name: polkadot-wss
    {{- end }}
    {{- if .Values.dojima_chain }}
    - port: {{ include "gateway-dojima-chain.http" . }}
      targetPort: dc-http
      protocol: TCP
      name: dc-http
    - port: {{ include "gateway-dojima-chain.rpc" . }}
      targetPort: dc-rpc
      protocol: TCP
      name: dc-rpc
    {{- end }}
    {{- if .Values.faucet }}
    - port: {{ include "gateway-dojima-chain.faucet" . }}
      targetPort: faucet
      protocol: TCP
      name: faucet
    {{- end }}
  selector:
    {{- include "gateway.selectorLabels" . | nindent 4 }}
