dojima-wallet:
  image:
    name: 576263512135.dkr.ecr.ap-south-1.amazonaws.com/core/dojima-wallet
    tag: 2022-07-15_v0.0.6
  env:
    ENV: prod


landing-page:
  image:
    name: 576263512135.dkr.ecr.ap-south-1.amazonaws.com/dojima-landing-page
    tag: 2022-07-15_v0.0.4
  env:
    ENV: prod    


internal-docs:
  image:
    name: 576263512135.dkr.ecr.ap-south-1.amazonaws.com/internal-docs
    tag: 2022-06-16_v0.0.1
  env:
    ENV: prod