dojima-wallet:
  image:
    name: 576263512135.dkr.ecr.ap-south-1.amazonaws.com/core/dojima-wallet
    tag: 2022-07-29_v0.0.7
  env:
    ENV: stage


landing-page:
  image:
    name: 576263512135.dkr.ecr.ap-south-1.amazonaws.com/dojima-landing-page
    tag: 2022-09-02_v0.0.2
  env:
    ENV: stage 


block-explorer:
  image:
    name: 576263512135.dkr.ecr.ap-south-1.amazonaws.com/dojima-block-explorer
    tag: test_2022-12-13_v0.0.1
  env:
    ENV: stage        


internal-docs:
  image:
    name: 576263512135.dkr.ecr.ap-south-1.amazonaws.com/internal-docs
    tag: 2022-06-16_v0.0.1
  env:
    ENV: stage


developer-docs:
  image:
    name: 576263512135.dkr.ecr.ap-south-1.amazonaws.com/developer-docs
    tag: 2022-08-02_0.1.1
  env:
    ENV: stage    