global:
  net: testnet
  gateway:
    enabled: true
    name: frontend-gateway
  images:
    alpine:
      tag: latest
      hash: 4edbd2beb5f78b1014028f4fbb99f3237d9561100b6881aabbf5acce2c4f9454
    alpineK8s:
      tag: 1.18.2
      hash: 768491682ca99e14498ddb62973a95a664a0525ca18e7ad0eaab2621d3124f5b
    busybox:
      tag: latest
      hash: caa382c432891547782ce7140fb3b7304613d3b0438834dce1cad68896ab110a

frontend-gateway:
  fullnameOverride: frontend-gateway
  enabled: true

landing-page:
  fullnameOverride: landing-page
  enabled: true

dojima-wallet:
  fullnameOverride: dojima-wallet
  enabled: true

block-explorer:
  fullnameOverride: block-explorer
  enabled: true