# Default values for narada.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

net: stagenet

ethSuggestedFeeVersion:
  mainnet: 1
  stagenet: 2
  testnet: 2
  mocknet: 1

narada_log_level: "info"

signer:
  name: hermeschain
  password: password
  mnemonicSecret: ""
  passwordSecret: ""

chain_home_folder: /root/.hermesnode

environment:
  INCLUDE_ETH_CHAIN: true
  INCLUDE_BINANCE_CHAIN: false
  INCLUDE_BTC_CHAIN: false
  INCLUDE_AR_CHAIN: false
  INCLUDE_DOT_CHAIN: false
  INCLUDE_SOL_CHAIN: false
  INCLUDE_GAIA_CHAIN: false
  INCLUDE_DOJ_CHAIN: true
  INCLUDE_AVAX_CHAIN: false
  DOJIMA_SPAN_ENABLE: true
  AVAX_HOST: http://avalanche-daemon.hermes-stagenet:9650/ext/bc/C/rpc
  TSS_P2P_PORT: 5040
  P2P_ID_PORT: 6040
  EDDSA_HOST: narada-eddsa:6050
  DOJ_CHAIN_ID: 1401
  DOJ_HOST: http://dojima-chain:8545
  DOJ_START_BLOCK_HEIGHT: 0
  CHAIN_API: hermesnode:1317
  CHAIN_RPC: hermesnode:26657
  VALIDATOR: true
  DOJIMA_RPC_URL: http://dojima-chain:8545

# use in multi nodes envs
narada_peer:

external_ip:

debug: true

dojima_chain:
  rpc_url: http://dojima-chain:8545
  grpc_url: hermesnode:9090
  chain_id: 1401

hermesApi: hermesnode:1317
chainID:
  testnet: hermes-testnet-v2
#  mainnet: thorchain-mainnet-v1
  stagenet: hermeschain-stagenet
#  mocknet: hermes_mocknet

hermesDaemon:
#  mainnet: hermesnode:27147
  testnet: hermesnode:26657
  stagenet: hermesnode:26657
#  mocknet: hermesnode:26657

arweaveDaemon:
  enabled: true
  testnet: http://arweave-daemon:1984
  arweaveStartBlockHeight: 0

polkaDaemmon:
  enabled: true
  testnet: ws://polkadot-daemon.hermes-devnet:9944
  stagenet: wss://dotws.h4s.dojima.network:9944
  polkaStartBlockHeight: 0

solanaDaemon:
  enabled: true
  testnet: http://solana-daemon:8899
  wsTestnet: wss://solws.h4s.dojima.network:8900
  solanaStartBlockHeight: 0


binanceDaemon:
  enabled: false
#  mainnet: http://binance-daemon:27147
  testnet: http://binance-daemon.hermes-devnet:26657
  stagenet: http://binance-daemon.hermes-stagenet:26657
  mocknet: http://binance-daemon:26660
  binanceStartBlockHeight: 0

bitcoinDaemon:
  enabled: false
#  mainnet: bitcoin-daemon:8332
  testnet: bitcoin-daemon.hermes-devnet:18332
#  mocknet: bitcoin-daemon:18443
  stagenet: bitcoin-daemon.hermes-stagenet:8332
  bitcoinStartBlockHeight: 0

ethereumDaemon:
  enabled: true
#  mainnet: http://ethereum-daemon:8545
  testnet: http://ethereum-daemon.hermes-devnet:9545
#  mocknet: http://ethereum-daemon:8545
  stagenet: https://eth.h4s.dojima.network:80
  ethereumStartBlockHeight: 0

gaiaDaemon:
  enabled: true
#  mainnet:
#    rpc: http://gaia-daemon:26657
#    grpc: gaia-daemon:9090
#    grpcTLS: false
  stagenet:
    rpc: http://gaia-daemon.hermes-stagenet:26657
    grpc: gaia-daemon:9090
    grpcTLS: false
  testnet:
    rpc: http://gaia-daemon.hermes-devnet:26657
    grpc: gaia-daemon:9090
  gaiaStartBlockHeight: 0


replicaCount: 1

strategyType: Recreate

image:
  repository: asia-south1-docker.pkg.dev/prod-dojima/testnet/hermes
  pullPolicy: IfNotPresent
  tag: 76910312_3.0.2
  hash: "af37838a6800e4e866c4e42e2aace980ccdd6861bd983eb94dfc015a15f8ed39" # Not used for mocknet/testnet

imagePullSecrets: []
nameOverride: "narada"
fullnameOverride: "narada"

persistence:
  enabled: true
  size:
    testnet: 10Gi
#    mainnet: 50Gi
    stagenet: 10Gi
#    mocknet: 10Gi
  accessMode: ReadWriteOnce
  # existingClaim: your-pvc
#  storageClass: gp2
  # hostPath: /host-path

service:
  type: ClusterIP
  port:
    p2p: 5040
    http: 6040
    nqs: 6049
    prometheus: 9000

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "serv-node-narada"

priorityClassName: ""

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# service:
#   type: ClusterIP
#   port: 80

resources:
  requests:
    cpu: 4
    memory: 3Gi
  limits:
    memory: 4Gi

nodeSelector: {}

tolerations: []

affinity: {}

global:
  gateway:
    enabled: false
  images:
    alpineK8s:
      tag: 1.18.2
      hash: 768491682ca99e14498ddb62973a95a664a0525ca18e7ad0eaab2621d3124f5b
    busybox:
      tag: latest
      hash: caa382c432891547782ce7140fb3b7304613d3b0438834dce1cad68896ab110a