# Default values for binance-daemon.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

net: testnet

replicaCount: 1

image:
  name: 576263512135.dkr.ecr.ap-south-1.amazonaws.com/solana-anchor
  tag: "mainnet-0.1.0-2022-12-16"
  hash: "99a9a9a79d61b5424a1ae605b12eb4e5bafd098713ad18c1d252c523cb04e4c1"
  testnet: "solanalabs/solana:stable"

imagePullSecrets: []
nameOverride: "solana-daemond"
fullnameOverride: "fsolana-daemond"

recoverNineRealmsSnapshot: false

service:
  type: ClusterIP
  port:
    testnet:
      rpc: 8899
      ws: 8900
      udp: 8003
      gossip: 1024
      tpu: 1027
    stagenet:
      rpc: 8899
      ws: 8900
      udp: 8003
      gossip: 1024
      tpu: 1027
    mainnet:
      rpc: 8899
      ws: 8900
      udp: 8003
      gossip: 1024
      tpu: 1027

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # cert-manager.io/cluster-issuer: letsencrypt-production
  hosts: []
    # - host: midgard.example.com
    #   paths:
    #   - path: /
    #     backend:
    #       serviceName: gateway
    #       servicePort: midgard
  tls: []
    # - secretName: midgard-tls
    #   hosts:
    #     - midgard.example.com

persistence:
  enabled: true
  size:
    testnet: 200Gi
    stagenet: 500Gi
    mainnet: 500Gi
  accessMode: ReadWriteOnce
  # storageClass: "-"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "serv-solana-daemon"

podSecurityContext:
  fsGroup: 1000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  requests:
    cpu: 4
    memory: 4Gi
  limits:
    # cpu: 2
    memory: 4Gi

nodeSelector: {}

tolerations: []

affinity: {}


global:
  tag:
  net: testnet
  peer:
  passwordSecret:
  mnemonicSecret:
  gateway:
    enabled: true
    name: "hermesnode-gateway"
  images:
    alpineK8s:
      tag: 1.18.2
      hash: 768491682ca99e14498ddb62973a95a664a0525ca18e7ad0eaab2621d3124f5b
    busybox:
      tag: latest
      hash: caa382c432891547782ce7140fb3b7304613d3b0438834dce1cad68896ab110a

