apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "landing-page-daemon.fullname" . }}
  labels:
    {{- include "landing-page-daemon.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "landing-page-daemon.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "landing-page-daemon.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "landing-page-daemon.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init-external-ip
          image: "alpine/k8s:{{ .Values.global.images.alpineK8s.tag }}@sha256:{{ .Values.global.images.alpineK8s.hash }}"
          {{- if .Values.global.gateway.enabled }}
          command: [ '/scripts/external-ip.sh', 'false', '{{ .Values.global.gateway.name }}', '{{ include "landing-page-daemon.fullname" . }}-external-ip' ]
          {{- else }}
          command: [ '/scripts/external-ip.sh', 'false', '{{ include "landing-page-daemon.fullname" . }}', '{{ include "landing-page-daemon.fullname" . }}-external-ip' ]
          {{- end }}
          volumeMounts:
            - name: scripts
              mountPath: /scripts
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "landing-page-daemon.image" . }}
          imagePullPolicy: IfNotPresent
          env:
            - name: REACT_APP_DOJIMA_WALLET_URL
              value: {{ .Values.env.dojima_wallet_url }}
            - name: REACT_APP_DOJIMA_NETWORK_LOGO
              value: {{ .Values.env.dojima_network_logo }}
            - name: REACT_APP_DOJIMA_TOKEN_LOGO
              value: {{ .Values.env.dojima_token_logo }}
            - name: REACT_APP_API_KEY
              value: {{ .Values.env.api_key }}
            - name: REACT_APP_AUTH_DOMAIN
              value: {{ .Values.env.auth_domain }}
            - name: REACT_APP_DATABASE_URL
              value: {{ .Values.env.database_url }}
            - name: REACT_APP_PROJECT_ID
              value: {{ .Values.env.project_id }}
            - name: REACT_APP_STORAGE_BUCKET
              value: {{ .Values.env.storage_bucket }}
            - name: REACT_APP_MESSAGING_SENDER_ID
              value: "{{ .Values.env.messaging_sender_id }}"
            - name: REACT_APP_APP_ID
              value: {{ .Values.env.app_id }}
            - name: REACT_APP_MEASUREMENT_ID
              value: {{ .Values.env.measurement_id }}
            - name: GENERATE_SOURCEMAP
              value: "{{ .Values.env.generate_sourcemap }}"
          ports:
            - name: http
              containerPort: {{ include "landing-page-daemon.http" . }}
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: http
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
            initialDelaySeconds: 90
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: http
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
            initialDelaySeconds: 60
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: data
      {{- if and .Values.persistence.enabled (not .Values.persistence.hostPath) }}
        persistentVolumeClaim:
          claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ template "landing-page-daemon.fullname" . }}{{- end }}
      {{- else if and .Values.persistence.enabled .Values.persistence.hostPath }}
        hostPath:
          path: {{ .Values.persistence.hostPath }}
          type: DirectoryOrCreate
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: scripts
        configMap:
          name: {{ include "landing-page-daemon.fullname" . }}-scripts
          defaultMode: 0777
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
