# Default values for narada.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

net: testnet

crawler_log_level: "info"

signer:
  name: ""
  password: ""
  mnemonicSecret: ""
  passwordSecret: ""

environment:
  DOJ_CHAIN_ID: 184
  HERMES_API: hermesnode:1317
  HERMES_GRPC: hermesnode:9090
  HERMES_TENDERMINT_URL: hermesnode:26657
  HTTP_AUTH_HANDLER_PORT: "0.0.0.0:1219"
  PORT: "0.0.0.0:8090"
  HTTP_AUTH_HOST: 0.0.0.0
  HTTP_AUTH_PORT: 1219
  DOT_HOST: polkadot-daemon.operator-gateway-1
  SOL_HOST: 4.186.24.152
  ETH_HOST: ethereum-daemon.operator-gateway-1


replicaCount: 1

strategyType: Recreate

image:
  repository: asia-south1-docker.pkg.dev/prod-dojima/testnet/hermes
  pullPolicy: IfNotPresent
  tag: 76910312_3.0.2
  hash: "af37838a6800e4e866c4e42e2aace980ccdd6861bd983eb94dfc015a15f8ed39" # Not used for mocknet/testnet

nginx:
  name: testnet1.azurecr.io/operator-gateway-nginx
  tag: 15af188_1.0.0

imagePullSecrets: []
nameOverride: "operator-gateway"
fullnameOverride: "operator-gateway"

persistence:
  enabled: false
  size:
    testnet: 10Gi
#    mainnet: 50Gi
    stagenet: 10Gi
#    mocknet: 10Gi
  accessMode: ReadWriteOnce
  # existingClaim: your-pvc
#  storageClass: gp2
  # hostPath: /host-path

service:
  type: LoadBalancer
  port:
    http: 1219
    grpc: 8090
    sol: 9002
    eth: 9003
    dot: 9004
    btc: 9005
    token: 9045

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "operator-gateway"

priorityClassName: ""

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# service:
#   type: ClusterIP
#   port: 80

resources:
  gateway:
    requests:
      cpu: 1m
      memory: 0.5Gi
    limits:
      cpu: 1m
      memory: 1Gi
  nginx:
    requests:
      cpu: 1m
      memory: 0.5Gi
    limits:
      cpu: 1m
      memory: 1Gi


nodeSelector: {}

tolerations: []

affinity: {}

global:
  gateway:
    enabled: false
  images:
    alpineK8s:
      tag: 1.18.2
      hash: 768491682ca99e14498ddb62973a95a664a0525ca18e7ad0eaab2621d3124f5b
    busybox:
      tag: latest
      hash: caa382c432891547782ce7140fb3b7304613d3b0438834dce1cad68896ab110a