name: dojima-faas

replicaCount: 1
serverPort: 3000
prometheusPort: 7071
uriPrefix: /dojima-faas
servicePortName: dojima-faas-fe-port

image:
  name: 576263512135.dkr.ecr.ap-south-1.amazonaws.com/dojima-faas
  tag: 2022-09-01_v0.0.3

strategy:
  enable: false
  maxSurge: 2
  maxUnavailable: 1

resources:
  enable: false
  requestsMemory: 30Mi
  requestsCpu: 10m
  limitsMemory: 90Mi
  limitsCpu: 50m

hpa:
  enable: false
  maxReplicas: 5
  minReplicas: 3
  hpaCpu: 370
  hpaMemory: 240
