apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "polkadot-daemon.fullname" . }}
  labels:
    {{- include "polkadot-daemon.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "polkadot-daemon.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "polkadot-daemon.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "polkadot-daemon.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init-external-ip
          image: "alpine/k8s:{{ .Values.global.images.alpineK8s.tag }}@sha256:{{ .Values.global.images.alpineK8s.hash }}"
          {{- if .Values.global.gateway.enabled }}
          command: [ '/scripts/external-ip.sh', 'false', '{{ .Values.global.gateway.name }}', '{{ include "polkadot-daemon.fullname" . }}-external-ip' ]
          {{- else }}
          command: [ '/scripts/external-ip.sh', 'false', '{{ include "polkadot-daemon.fullname" . }}', '{{ include "polkadot-daemon.fullname" . }}-external-ip' ]
          {{- end }}
          volumeMounts:
            - name: scripts
              mountPath: /scripts
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "polkadot-daemon.image" . }}
          imagePullPolicy: IfNotPresent
          command:
            - polkadot
            - --rpc-external
            - --ws-external
            - --rpc-cors=all
            - --prometheus-external
          {{- if eq .Values.net "testnet" }}
            - --chain={{ .Values.chain.testnet }}
          {{- else if eq .Values.net "mainnet" }}
            - --chain={{ .Values.chain.mainnet }}
          {{- else }}
            - --dev
            - --name=dojima-polka-testnet
            - --state-pruning=archive
            - --blocks-pruning=archive
            - --base-path=/data/.{{ .Values.chain.devnet }}
          {{- end }}
          ports:
            - name: p2p
              containerPort: {{ include "polkadot-daemon.p2p" . }}
              protocol: TCP
            - name: http
              containerPort: {{ include "polkadot-daemon.http" . }}
              protocol: TCP
            - name: ws
              containerPort: {{ include "polkadot-daemon.ws" . }}
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: data
          resources:
          {{- if not (eq (include "polkadot-daemon.net" . ) "mocknet") }}
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
      volumes:
      - name: data
      {{- if and .Values.persistence.enabled (not .Values.persistence.hostPath) }}
        persistentVolumeClaim:
          claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ template "polkadot-daemon.fullname" . }}{{- end }}
      {{- else if and .Values.persistence.enabled .Values.persistence.hostPath }}
        hostPath:
          path: {{ .Values.persistence.hostPath }}
          type: DirectoryOrCreate
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: scripts
        configMap:
          name: {{ include "polkadot-daemon.fullname" . }}-scripts
          defaultMode: 0777
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
