apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
  annotations:
    # AWS
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-south-1:576263512135:certificate/36a81c43-d2f2-4d33-8ff6-cbb564684ba3
    service.beta.kubernetes.io/aws-load-balancer-eip-allocations: eipalloc-096d09ca6c39c6f15,eipalloc-02498d42f97db2060,eipalloc-036c8aedd95b0ef73
    # Only run SSL on the port named "https" below.
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https,faucet
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: Local
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
    {{- if .Values.domain.faucet.enable }}
    - port: {{ include "gateway-dojima-chain.faucet" . }}
      targetPort: faucet
      protocol: TCP
      name: faucet
    {{- end }}
    {{- if .Values.domain.fiber.testnet.enable }}
    - port: {{ .Values.service.port.fiber.testnet.api }}
      targetPort: bex-fiber
      protocol: TCP
      name: bex-fiber
    {{- end }}
  selector:
    {{- include "gateway.selectorLabels" . | nindent 4 }}
