apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "crawler.fullname" . }}
  labels:
    {{- include "crawler.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.strategyType }}
  selector:
    matchLabels:
      {{- include "crawler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "crawler.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '9000'
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "crawler.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}

      initContainers:
      - name: init-external-ip
        image: "alpine/k8s:{{ .Values.global.images.alpineK8s.tag }}@sha256:{{ .Values.global.images.alpineK8s.hash }}"
        {{- if .Values.global.gateway.enabled }}
        command: ['/scripts/external-ip.sh', 'false', '{{ .Values.global.gateway.name }}', '{{ include "crawler.fullname" . }}-external-ip']
        {{- else }}
        command: ['/scripts/external-ip.sh', 'false', '{{ include "crawler.fullname" . }}', '{{ include "crawler.fullname" . }}-external-ip']
        {{- end }}
        volumeMounts:
        - name: scripts
          mountPath: /scripts
      - name: init-keepalive
        image: "busybox:{{ .Values.global.images.busybox.tag }}@sha256:{{ .Values.global.images.busybox.hash }}"
        command:
        - /bin/sh
        - -c
        - |
          sysctl -w net.ipv4.tcp_keepalive_time=120
          sysctl -w net.ipv4.tcp_keepalive_intvl=60
          sysctl -w net.ipv4.tcp_keepalive_probes=3
        securityContext:
          privileged: true
      - name: generate-keystore
        image: {{ include "crawler.hermesnode-image" . }}
        command: [ 'sh', '-c', '/scripts/genesis.sh' ]
        env:
          - name: SIGNER_NAME
            value: {{ .Values.signer.name }}
          - name: SIGNER_PASSWD
            {{- if default .Values.signer.passwordSecret .Values.global.passwordSecret }}
            valueFrom:
              secretKeyRef:
                name: {{ default .Values.signer.passwordSecret .Values.global.passwordSecret }}
                key: password
            {{- else }}
            value: {{ .Values.signer.password }}
            {{- end }}
          {{- if default .Values.signer.mnemonicSecret .Values.global.mnemonicSecret }}
          - name: SIGNER_SEED_PHRASE
            valueFrom:
              secretKeyRef:
                name: {{ default .Values.signer.mnemonicSecret .Values.global.mnemonicSecret }}
                key: mnemonic
          {{- end }}
          - name: CHAIN_ID
            value: "{{ include "crawler.chainID" . }}"
          {{- range $key, $value := .Values.environment }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
        volumeMounts:
          - name: data
            mountPath: /root
          - name: scripts
            mountPath: /kube-scripts/
      - name: init-hermeschain
        image: "busybox:{{ .Values.global.images.busybox.tag }}@sha256:{{ .Values.global.images.busybox.hash }}"
        command: ['sh', '-c', 'until nc -zv {{ .Values.hermesApi }}; do echo waiting for hermesnode; sleep 2; done']
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "crawler.image" . }}
          command: ["/scripts/crawler.sh", "crawler", "-c", "/etc/crawler/config.json"]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /var/data/crawler
              name: data
              subPath: data
            - mountPath: /root
              name: data
            - mountPath: /etc/crawler
              name: data
              subPath: etc
          env:
            - name: EXTERNAL_IP
              valueFrom:
                configMapKeyRef:
                  name: {{ include "crawler.fullname" . }}-external-ip
                  key: externalIP
            - name: NET
              value: {{ include "crawler.net" . }}
            - name: BINANCE_HOST
              value: {{ include "crawler.binanceDaemon" . }}
            - name: BINANCE_START_BLOCK_HEIGHT
              value: "{{ .Values.binanceDaemon.binanceStartBlockHeight }}"
            - name: BTC_HOST
              value: {{ include "crawler.bitcoinDaemon" . }}
            - name: BTC_START_BLOCK_HEIGHT
              value: "{{ .Values.bitcoinDaemon.bitcoinStartBlockHeight }}"
            - name: AR_HOST
              value: {{ include "crawler.arweaveDaemon" . }}
            - name: AR_START_BLOCK_HEIGHT
              value: "{{ .Values.arweaveDaemon.arweaveStartBlockHeight }}"
            - name: DOT_HOST
              value: {{ include "crawler.polkaDaemon" . }}
            - name: DOT_START_BLOCK_HEIGHT
              value: "{{ .Values.polkaDaemon.polkaStartBlockHeight }}"
            - name: SOL_HOST
              value: {{ include "crawler.solanaDaemon" . }}
            - name: SOL_HOST_WS
              value: {{ include "crawler.solanaWsDaemon" . }}
            {{- if not .Values.gaiaDaemon.enabled }}
            - name: GAIA_DISABLED
              value: "true"
            {{- end }}
            - name: ETH_HOST
              value: {{ include "crawler.ethereumDaemon" . }}
            - name: ETH_START_BLOCK_HEIGHT
              value: "{{ .Values.ethereumDaemon.ethereumStartBlockHeight }}"
            - name: ETH_SUGGESTED_FEE_VERSION
              value: '{{ include "crawler.ethSuggestedFeeVersion" . }}'
            - name: SEED
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SIGNER_NAME
              value: {{ .Values.signer.name }}
              - name: SIGNER_PASSWD
                {{- if default .Values.signer.passwordSecret .Values.global.passwordSecret }}
                valueFrom:
                  secretKeyRef:
                    name: {{ default .Values.signer.passwordSecret .Values.global.passwordSecret }}
                    key: password
                {{- else }}
                value: {{ .Values.signer.password }}
                {{- end }}
            {{- if default .Values.signer.mnemonicSecret .Values.global.mnemonicSecret }}
            - name: SIGNER_SEED_PHRASE
              valueFrom:
                secretKeyRef:
                  name: {{ default .Values.signer.mnemonicSecret .Values.global.mnemonicSecret }}
                  key: mnemonic
            {{- end }}
            - name: CHAIN_ID
              value: {{ .Values.global.hermes.chainId }}
            - name: DB_PATH
              value: /var/data
            - name: DOJIMA_CHAIN_ID
              value: {{ .Values.global.dojimachain.chainId | quote }}
            - name: DOJIMA_GRPC_URL
              value: {{ .Values.dojima_chain.grpc_url | quote }}
            - name: PEER
              value: {{ default .Values.peer .Values.crawler_peer | quote }}
            {{- range $key, $value := .Values.environment }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          ports:
            - name: p2p
              containerPort: {{ .Values.service.port.p2p }}
              protocol: TCP
            - name: http
              containerPort: {{ .Values.service.port.http }}
              protocol: TCP
            - name: prometheus
              containerPort: {{ .Values.service.port.prometheus }}
              protocol: TCP
            - name: nqs
              containerPort: {{ include "crawler-nqs.port" . }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      volumes:
      - name: data
        {{- if and .Values.persistence.enabled (not .Values.persistence.hostPath) }}
        persistentVolumeClaim:
          claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ template "crawler.fullname" . }}{{- end }}
        {{- else if and .Values.persistence.enabled .Values.persistence.hostPath }}
        hostPath:
          path: {{ .Values.persistence.hostPath }}
          type: DirectoryOrCreate
        {{- else }}
        emptyDir: {}
        {{- end }}
      - name: scripts
        configMap:
          name: {{ include "crawler.fullname" . }}-scripts
          defaultMode: 0777
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
    affinity:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
    tolerations:
      {{- toYaml . | nindent 8 }}
    {{- end }}
