{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "crawler.serviceAccountName" . }}
  labels:
{{ include "crawler.labels" . | nindent 4 }}
{{- end -}}
