apiVersion: v1
kind: Service
metadata:
  name: {{ include "dojima-chain.fullname" . }}
  labels:
    {{- include "dojima-chain.labels" . | nindent 4 }}
  annotations:
    # AWS
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: {{ .Values.service.type }}
  {{- if ne "ClusterIP" .Values.service.type }}
  externalTrafficPolicy: Local
  {{- end }}
  ports:
    - port: {{ .Values.service.port.testnet.http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.port.testnet.wss }}
      targetPort: wss
      protocol: TCP
      name: wss
    - name: devp2p
      port: {{ .Values.service.port.testnet.devp2p }}
      targetPort: devp2p
      protocol: TCP
    - name: graphql
      port: {{ .Values.service.port.testnet.graphql }}
      targetPort: graphql
      protocol: TCP
  selector:
    {{- include "dojima-chain.selectorLabels" . | nindent 4 }}
