# ConfigMap to store shell scripts
apiVersion: v1
kind: ConfigMap
metadata:
  name: token-bridge-scripts
  namespace: arbitrum-rollup-1
data:
  deploy.sh: |
    #!/bin/sh
    echo "Deploying contracts..."
    # Add your contract deployment logic here
    echo "Deployment complete!"
---
apiVersion: v1
kind: Pod
metadata:
  name: token-bride-contracts-arbitrum
  namespace: arbitrum-rollup-1
spec:
  initContainers:
    - name: init-deploy-contracts
      image: "node:18-bullseye-slim"
      command: ['/scripts/deploy.sh']
      volumeMounts:
        - mountPath: /scripts
          name: script-config
  containers:
    - name: arbitrum-token-bridge-finish
      image: alpine:latest
      command:
        - sh
        - -c
        - |
          echo "InitContainer complete. This container is here to satisfy Kubernetes requirements."
      resources:
        requests:
          cpu: "10m"
          memory: "16Mi"
  restartPolicy: Never
  volumes:
    - name: script-config
      configMap:
        name: token-bridge-scripts