apiVersion: v1
kind: ConfigMap
metadata:
  name: token-bridge-scripts
  namespace: '${NAME}'
data:
  deploy.sh: |
    #!/bin/sh
    set -eu pipefail
    
    apt-get update && \
    apt-get install -y git docker.io python3 build-essential
  
    
    # Set up working directory
    WORKSPACE_DIR="/workspace"
    mkdir -p "$WORKSPACE_DIR"
    cd "$WORKSPACE_DIR"
    
    git clone --no-checkout https://github.com/dojimanetwork/token-bridge-contracts.git ./
    git checkout develop
    
    yarn install
    yarn build
    
    yarn deploy:local:token-bridge
---
apiVersion: v1
kind: Pod
metadata:
  name: token-bridge-contracts-arbitrum
  namespace: '${NAME}'
spec:
  initContainers:
    - name: init-deploy-contracts
      image: "node:18-bullseye-slim"
      command: ['sh', '/scripts/deploy.sh']
      env:
        - name: ROLLUP_OWNER_KEY
          valueFrom:
            secretKeyRef:
              name: "${DEPLOYER_PRIVKEY_NAME}"
              key: deployer_priv_key
        - name: ROLLUP_ADDRESS
          value: "${ROLLUP_ADDR}"
        - name: PARENT_KEY
          valueFrom:
            secretKeyRef:
              name: "${DEPLOYER_PRIVKEY_NAME}"
              key: deployer_priv_key
        - name: PARENT_RPC
          value: https://rpc-test-d11k.dojima.network
        - name: CHILD_KEY
          valueFrom:
            secretKeyRef:
              name: "${DEPLOYER_PRIVKEY_NAME}"
              key: deployer_priv_key
        - name: CHILD_RPC
          value: "http://${BS_EXTERNAL_IP}:8547"
        - name: DEPLOYMENT_JSON
          value: '${DEPLOYMENT_JSON}'
      volumeMounts:
        - mountPath: /scripts
          name: script-config
        - mountPath: /workspace
          name: workspace
  containers:
    - name: arbitrum-token-bridge-finish
      image: alpine:latest
      command:
        - sh
        - -c
        - |
          sleep infinity
      resources:
        requests:
          cpu: "10m"
          memory: "16Mi"
      volumeMounts:
        - mountPath: /scripts
          name: script-config
        - mountPath: /workspace
          name: workspace
  restartPolicy: Never
  volumes:
    - name: script-config
      configMap:
        name: token-bridge-scripts
    - name: workspace
      emptyDir: { }
