# Default values for binance-daemon.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

net: testnet

replicaCount: 1

image:
  name: 576263512135.dkr.ecr.ap-south-1.amazonaws.com/dojima-landing-page
  testnet: "testnet-0.1.14-2022-12-26"
  mainnet: "mainnet-0.1.11-2022-12-22"
  testnet_hash: "a5862334d02357fff21647433b19bdf5f9edbfa1d9233bd2762283bf5c65b0f0"
  mainnet_hash: "c9d07e2bf2a5fdfad41b0bdad14cdee7060c6f97513f4c001a6236811120d6ed"

imagePullSecrets: []
nameOverride: "landing-paged"
fullnameOverride: "landing-paged"

recoverNineRealmsSnapshot: false

env:
  dojima_wallet_url: https://wallet.dojima.network/wallet/get-started
  dojima_network_logo: https://dojima-brand-images.s3.ap-south-1.amazonaws.com/dojimanetworklogo.zip
  dojima_token_logo: https://dojima-brand-images.s3.ap-south-1.amazonaws.com/dojimalogo.zip
  api_key: "AIzaSyAacJtbWs09ItdyfEQ5XqPczWCDvf47IpA"
  auth_domain: "dojima-wallet-d3638.firebaseapp.com"
  database_url: "https://dojima-wallet-d3638-default-rtdb.firebaseio.com"
  project_id: "dojima-wallet-d3638"
  storage_bucket: "dojima-wallet-d3638.appspot.com"
  messaging_sender_id: "462805295807"
  app_id: "1:462805295807:web:d659bfab5dd48f87045c0a"
  measurement_id: "G-KJFKE93ST6"
  generate_sourcemap: false

service:
  type: ClusterIP
  port:
    testnet:
      http: 80
    stagenet:
      http: 80
    mainnet:
      http: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # cert-manager.io/cluster-issuer: letsencrypt-production
  hosts: []
    # - host: midgard.example.com
    #   paths:
    #   - path: /
    #     backend:
    #       serviceName: gateway
    #       servicePort: midgard
  tls: []
    # - secretName: midgard-tls
    #   hosts:
    #     - midgard.example.com

persistence:
  enabled: false
  size:
    testnet: 50Gi
    stagenet: 500Gi
    mainnet: 500Gi
  accessMode: ReadWriteOnce
  # storageClass: "-"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "serv-frontend-landing-page"

podSecurityContext:
  fsGroup: 1000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  requests:
    cpu: 1
    memory: 2Gi
  limits:
#     cpu: 2
    memory: 3Gi

nodeSelector: {}

tolerations: []

affinity: {}


global:
  tag:
  net: testnet
  peer:
  passwordSecret:
  mnemonicSecret:
  gateway:
    enabled: false
    name: "frontend-gateway"
  images:
    alpineK8s:
      tag: 1.18.2
      hash: 768491682ca99e14498ddb62973a95a664a0525ca18e7ad0eaab2621d3124f5b
    busybox:
      tag: latest
      hash: caa382c432891547782ce7140fb3b7304613d3b0438834dce1cad68896ab110a

