name: landing-page

replicaCount: 1
serverPort: 80
prometheusPort: 7071
uriPrefix: /landing-page
servicePortName: landing-page-fe-port

image:
  name: 576263512135.dkr.ecr.ap-south-1.amazonaws.com/dojima-landing-page
  tag: 2022-08-02_v0.0.8

strategy:
  enable: false
  maxSurge: 2
  maxUnavailable: 1

resources:
  enable: false
  requestsMemory: 30Mi
  requestsCpu: 10m
  limitsMemory: 90Mi
  limitsCpu: 50m

hpa:
  enable: false
  maxReplicas: 5
  minReplicas: 3
  hpaCpu: 370
  hpaMemory: 240
