# Default values for binance-daemon.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

net: testnet

replicaCount: 1

image:
  name: 576263512135.dkr.ecr.ap-south-1.amazonaws.com/block-explorer-go
  tag: "mainnet-0.1.0-2023-01-18"
  hash: "859185d9c3b17bf3c9441793ebd020976bae8183c69ad6c484fd4fc2fed977e1"

imagePullSecrets: []
nameOverride: "bex-faucetd"
fullnameOverride: "fbex-faucetd"

recoverNineRealmsSnapshot: false


chain_home_folder: "/root/.hermesnode"
signer:
  name: hermeschain
  password: password
  mnemonicSecret: "password"
  passwordSecret: "password"
  #genesis phrase
  signer_seed_phrase: "wink umbrella toss bleak patient extend palm asthma divorce quit track planet depend tenant mimic shiver girl segment lend unit body account monster lizard"
  # validator 1 phrase
  # signer_seed_phrase: "pipe expire lecture state pilot latin stamp senior market much dilemma tooth airport oblige flower caught risk canoe radar gadget tag narrow inch trust"

chainID:
  testnet: "hermes-testnet"

hermes:
  testnet:
    image: 576263512135.dkr.ecr.ap-south-1.amazonaws.com/hermes/hermes-node
    tag: testnet-1.89.0_43
    hash: 904f8c6e368697039f1473e934cf7517112e6e89bdd0d558cceb5f39f7e40c52

env:
  mongo_uri: "mongodb+srv://Admin:6x4cuxFjT0DycMdx@cluster0.r9add7o.mongodb.net/?retryWrites=true&w=majority"
  ar_host: http://arweave-daemon:1984
  ar_amt: 1000000000000
  dot_host: ws://polkadot-daemon:9944
  mnemonic: "hero eagle luxury slight survey catch toy goat model general alarm inner"
  sol_host: http://solana-daemon:8899
  hermes_grpc_host: fhermesnode-hermes:9090
  hermes_host: http://fhermesnode-hermes:26657
  doj_host: http://dojima-chain:8545
  eth_host: http://ethereum-daemon:9545

service:
  type: ClusterIP
  port: 8081

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # cert-manager.io/cluster-issuer: letsencrypt-production
  hosts: []
    # - host: midgard.example.com
    #   paths:
    #   - path: /
    #     backend:
    #       serviceName: gateway
    #       servicePort: midgard
  tls: []
    # - secretName: midgard-tls
    #   hosts:
    #     - midgard.example.com

persistence:
  enabled: false
  size:
    testnet: 50Gi
    stagenet: 500Gi
    mainnet: 500Gi
  accessMode: ReadWriteOnce
  # storageClass: "-"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "serv-bex-faucet"

podSecurityContext:
  fsGroup: 1000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  requests:
    cpu: 2
    memory: 1Gi
  limits:
    # cpu: 2
    memory: 1Gi

nodeSelector: {}

tolerations: []

affinity: {}


global:
  tag:
  net: testnet
  peer:
  passwordSecret:
  mnemonicSecret:
  gateway:
    enabled: false
    name: "hermesnode-gateway"
  images:
    alpineK8s:
      tag: 1.18.2
      hash: 768491682ca99e14498ddb62973a95a664a0525ca18e7ad0eaab2621d3124f5b
    busybox:
      tag: latest
      hash: caa382c432891547782ce7140fb3b7304613d3b0438834dce1cad68896ab110a

