apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blockscout-v2-services.fullname" . }}-scripts
data:
  {{- range $key, $value := .Values.postgres.files.list }}
  {{ $key }}: {{ toYaml $value | indent 2 }}
  {{- end }}