# Default values for ethereum-daemon.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

net: mocknet

replicaCount: 1

image:
  eth:
    name: ethereum/client-go
    tag: "alltools-v1.10.26" # When tag is empty it defaults to the chart appVersion.
    hash: 03604c12f6123fda67f534c9a68a73dbabd35d5c0a13f0c6cfcf735cfd8760c8
  prysm:
    name: gcr.io/prysmaticlabs/prysm/beacon-chain
    tag: v3.1.2
    hash: 140aa344814fee97a5ef9ee873e69f4c851972b388588f74ea7d26b4842dc9c3
  scripts:
    repository: 576263512135.dkr.ecr.ap-south-1.amazonaws.com/hermes/hermes-node
    pullPolicy: IfNotPresent
    tag: testnet-1.89.0_58

chain: goerli
sync_url: https://goerli.checkpoint-sync.ethdevops.io
fee_recipient: 0x265e016835494F05170E460Dad7a9380Bd3a1BFf

imagePullSecrets: []
nameOverride: "narada-ethereumd"
fullnameOverride: "fnarada-ethereumd"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "serv-narada-ethereum"

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 9545
  wss: 9546

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # cert-manager.io/cluster-issuer: letsencrypt-production
  hosts: []
    # - host: midgard.example.com
    #   paths:
    #   - path: /
    #     backend:
    #       serviceName: gateway
    #       servicePort: midgard
  tls: []
    # - secretName: midgard-tls
    #   hosts:
    #     - midgard.example.com

persistence:
  enabled: true
  size:
    testnet: 50Gi
    stagenet: 900Gi
    mainnet: 1228Gi
  accessMode: ReadWriteOnce
  # storageClass: "-"
  #
resources:
  limits:
    # cpu: 1
    memory: 12Gi
  requests:
    cpu: 4
    memory: 12Gi

nodeSelector: {}

tolerations: []

affinity: {}

# necessary for lint
global:
  gateway:
    enabled: false
  images:
    alpineK8s:
      tag: 1.18.2
      hash: 768491682ca99e14498ddb62973a95a664a0525ca18e7ad0eaab2621d3124f5b
    busybox:
      tag: latest
      hash: caa382c432891547782ce7140fb3b7304613d3b0438834dce1cad68896ab110a
