# Default values for binance-daemon.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

net: testnet

replicaCount: 1

image:
  name: 576263512135.dkr.ecr.ap-south-1.amazonaws.com/dojima-block-explorer
  testnet: "testnet-0.1.29-2023-07-12"
  mainnet: ""
  testnet_hash: "076d3909d852f259b38f6059f47c2ceba70f7b64949378013c8414654d8cff46"
  mainnet_hash: ""

imagePullSecrets: []
nameOverride: "block-explorerd"
fullnameOverride: "block-explorerd"

recoverNineRealmsSnapshot: false

service:
  type: ClusterIP
  port:
    testnet:
      http: 82
    stagenet:
      http: 82
    mainnet:
      http: 82

env:
  hermes_api: https://api-test.h4s.dojima.network/
  hermes_rpc: https://rpc-test.h4s.dojima.network/

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # cert-manager.io/cluster-issuer: letsencrypt-production
  hosts: []
    # - host: midgard.example.com
    #   paths:
    #   - path: /
    #     backend:
    #       serviceName: gateway
    #       servicePort: midgard
  tls: []
    # - secretName: midgard-tls
    #   hosts:
    #     - midgard.example.com

persistence:
  enabled: false
  size:
    testnet: 50Gi
    stagenet: 500Gi
    mainnet: 500Gi
  accessMode: ReadWriteOnce
  # storageClass: "-"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "serv-frontend-block-explorer"

podSecurityContext:
  fsGroup: 1000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  requests:
    cpu: 0.3
    memory: 200Mi
  limits:
    cpu: 0.4
    memory: 400Mi

nodeSelector: {}

tolerations: []

affinity: {}


global:
  tag:
  net: testnet
  peer:
  passwordSecret:
  mnemonicSecret:
  gateway:
    enabled: false
    name: "frontend-gateway"
  images:
    alpineK8s:
      tag: 1.18.2
      hash: 768491682ca99e14498ddb62973a95a664a0525ca18e7ad0eaab2621d3124f5b
    busybox:
      tag: latest
      hash: caa382c432891547782ce7140fb3b7304613d3b0438834dce1cad68896ab110a

