# Default values for gateway.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

net: testnet

validator: true
midgard: false
grpc: true
rpc:
  enabled: true
  limited: false
api: true
arweave: true
solana: false
polkadot: true
dojima_chain: true
eth: true
binance: true

# whitelistIPs contains a list of allowed IP addresses or CIDRs. Defaults to allow all
# traffic if not provided.
whitelistIPs: []

replicaCount: 1

domain:
  h4s:
    testnet:
      api: api-test.h4s.dojima.network
      rpc: rpc-test.h4s.dojima.network
      ar: gcp-ar-test.h4s.dojima.network
      dot: dot-test.h4s.dojima.network
      dot_ws: dotws-test.h4s.dojima.network
      sol: sol-test.h4s.dojima.network
      sol_ws: solws-test.h4s.dojima.network
      eth: eth-test.h4s.dojima.network
      eth_ws: ethws-test.h4s.dojima.network
      bnb: bnb-test.h4s.dojima.network
  d11k:
    testnet:
      api: api-test.d11k.dojima.network
      wss: rpc-test.d11k.dojima.network
      graphql: graph-test.d11k.dojima.network
  faucet:
    api: faucet.h4s.dojima.network
  fiber:
    testnet:
      api: fiber-test.h4s.dojima.network


image:
  name: nginx
  tag: 1.21.0-alpine
  hash: cc8c413c74aba9fef9dae7f3da736725136bad1e3f24fbc93788aea1944f51c4

imagePullSecrets: []
# used for gateway.name
nameOverride: "hermesnode-gateway"
# used for gateway.fullname
fullnameOverride: "fhermesnode-gateway"

service:
  type: LoadBalancer
  port:
    narada:
      p2p: 5040
      api: 6040
    midgard: 8080
    api: 1317
    grpc: 9090
    mainnet:
      p2p: 27146
      rpc: 27147
    stagenet:
      p2p: 27146
      rpc: 27147
    testnet:
      p2p: 26656
      rpc: 26657
    arweave:
      testnet:
        api: 1984
    solana:
      testnet:
        rpc: 8899
        wss: 8900
        udp: 8003
        gossip: 1024
        tpu: 1027
    ethereum:
      testnet:
        api: 9545
        wss: 9546
    polkadot:
      testnet:
        wss: 9944
        http: 9933
    dc:
      testnet:
        http: 8545
        wss: 8546
        graphql: 8547
    faucet:
      testnet:
        api: 8040
    fiber:
      testnet:
        api: 7050
    binance:
      testnet:
        rpc: 26660

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "serv-node-gateway"

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # cert-manager.io/cluster-issuer: letsencrypt-production
  hosts: []
    # - host: midgard.example.com
    #   paths:
    #   - path: /
    #     backend:
    #       serviceName: gateway
    #       servicePort: midgard
  tls: []
    # - secretName: midgard-tls
    #   hosts:
    #     - midgard.example.com

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  limits:
    cpu: 0.1
    memory: 50Mi
  requests:
    cpu: 0.01
    memory: 20Mi

nodeSelector: {}

tolerations: []

affinity: {}

global:
  net:
  images:
    alpineK8s:
      tag: 1.18.2
      hash: sha256:768491682ca99e14498ddb62973a95a664a0525ca18e7ad0eaab2621d3124f5b
