name: internal-docs

replicaCount: 1
serverPort: 80
prometheusPort: 7071
uriPrefix: /internal-docs
servicePortName: carbon-fe-port

image:
  name: 576263512135.dkr.ecr.ap-south-1.amazonaws.com/internal-docs
  tag: 2022-05-17_v0.0.1

strategy:
  enable: false
  maxSurge: 2
  maxUnavailable: 1

resources:
  enable: false
  requestsMemory: 30Mi
  requestsCpu: 10m
  limitsMemory: 90Mi
  limitsCpu: 50m

hpa:
  enable: false
  maxReplicas: 5
  minReplicas: 3
  hpaCpu: 370
  hpaMemory: 240
