# Default values for hermes node

net: testnet
type: genesis

autoupdate:
  enable: false
  nodes:

chain_home_folder: "/root/.hermesnode"
ar_key_path: "/Users/luffybhaagi/dojima/ar-contracts/wallet-1.json"
ar_address: "2txTDSdb_RjG12uHZlVsB5jrfPzqxtzScKTtPef2KZ0"

signer:
  name: hermeschain
  password: password
  mnemonicSecret: "password"
  passwordSecret: "password"
  #genesis phrase
  signer_seed_phrase: "wink umbrella toss bleak patient extend palm asthma divorce quit track planet depend tenant mimic shiver girl segment lend unit body account monster lizard"
  # validator 1 phrase
  # signer_seed_phrase: "pipe expire lecture state pilot latin stamp senior market much dilemma tooth airport oblige flower caught risk canoe radar gadget tag narrow inch trust"


env:
  faucet_dest: 0x265e016835494F05170E460Dad7a9380Bd3a1BFf
  faucet_amt: 1000000000000000000
  eth_acc_pass: 0x265e016835494F05170E460Dad7a9380Bd3a1BFf

eth_host: http://ethereum-daemon:9545
dojima_rpc_url: http://dojima-chain:8545
peer:
seeds:
peerApi:
ethRouterContract:
  testnet: "0xefA28233838f46a80AaaC8c309077a9ba70D123A"

statesync:
  enabled: false
  seed: false
  trustHeight: 0
  trustHash: ""
  rpcServers:
  peer: ""

enableApi: true

debug: true

chainID:
  testnet: "hermes-testnet"

haltHeight: false

replicaCount: 1

strategyType: Recreate

image:
  repository: 576263512135.dkr.ecr.ap-south-1.amazonaws.com/hermes/hermes-node
  tag: testnet-1.89.0_57
  hash: sha256:904f8c6e368697039f1473e934cf7517112e6e89bdd0d558cceb5f39f7e40c52
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: "hermesnode-hermes"
fullnameOverride: "fhermesnode-hermes"

service:
  type: "ClusterIP"
  port:
    api: 1317
    testnet:
      p2p: 26656
      rpc: 26657
      grpc: 9090
      in_com: 26656
      abci: 26658
      prometheus_collector: 26661
      rosetta: 8080
      grpc_web: 9091
      pprof: 6060

persistence:
  enabled: true
  size:
    testnet: 300Gi
  accessMode: ReadWriteOnce

serviceAccount:
  create: true
  name: "serv-node-hermes"

priorityClassName: ""

podSecurityContext: {}

securityContext: {}

resources:
  requests:
    cpu: 4
    memory: 4Gi
  limits:

nodeSelector: {}

tolerations: []

affinity: {}

global:
  tag:
  net: testnet
  peer:
  passwordSecret:
  mnemonicSecret:
  gateway:
    enabled: false
    name: "hermesnode-gateway"
  images:
    alpineK8s:
      tag: 1.18.2
      hash: 768491682ca99e14498ddb62973a95a664a0525ca18e7ad0eaab2621d3124f5b
    busybox:
      tag: latest
      hash: caa382c432891547782ce7140fb3b7304613d3b0438834dce1cad68896ab110a


