# Default values for hermes node

net: testnet
type: genesis

autoupdate:
  enable: false
  nodes:

chain_home_folder: "/root/.hermesnode"
ar_key_path: "/Users/luffybhaagi/dojima/ar-contracts/wallet-1.json"
ar_address: "2txTDSdb_RjG12uHZlVsB5jrfPzqxtzScKTtPef2KZ0"

signer:
  name: hermeschain
  password: password
  mnemonicSecret: ""
  passwordSecret: ""

env:
  faucet_dest: 0x265e016835494F05170E460Dad7a9380Bd3a1BFf
  faucet_amt: 1000000000000000000
  eth_acc_pass: 0x265e016835494F05170E460Dad7a9380Bd3a1BFf

eth_host: http://ethereum-daemon:9545
dojima_rpc_url: http://dojima-chain:8545
peer:
seeds:
peerApi:
ethRouterContract:
  testnet: "0xefA28233838f46a80AaaC8c309077a9ba70D123A"

statesync:
  enabled: false
  seed: false
  trustHeight: 0
  trustHash: ""
  rpcServers:
  peer: ""

enableApi: true

debug: true

chainID:
  testnet: "hermes-testnet-v2"

haltHeight: false

replicaCount: 1

strategyType: Recreate

image:
  repository: asia-south1-docker.pkg.dev/prod-dojima/testnet/hermes
  tag: 3dcb6a5a_30-12-23
  hash: sha256:1a6a992dc6dcc5cee01c2541a6fc8a2ee10fccfbc2b085fa865efa2a9e8be7a2
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: "hermesnode"
fullnameOverride: "hermesnode"

hermesnode:
  environment:
    HERMESNODE_SERVICE_PORT_RPC:
      _default: 26657
    BINANCE_DAEMON_SERVICE_PORT_RPC:
      _default: 26657
    BINANCE_HOST:
      _default: binance-daemon
    BTC_HOST:
      _default: bitcoin-daemon
    ETH_HOST:
      _default: ethereum-daemon
    AVAX_HOST:
      _default: avalanche-daemon
    BITCOIN_DAEMON_SERVICE_PORT_RPC:
      _default: 18332
    ETHEREUM_DAEMON_SERVICE_PORT_RPC:
      _default: 9545
    AVALANCHE_DAEMON_SERVICE_PORT_RPC:
      _default: 9650


service:
  type: "ClusterIP"
  port:
    api: 1317
    testnet:
      p2p: 26656
      rpc: 26657
      grpc: 9090
      in_com: 26656
      abci: 26658
      prometheus_collector: 26661
      rosetta: 8080
      grpc_web: 9091
      pprof: 6060

persistence:
  enabled: true
  name: hermes-testnet-pv-1
  size:
    testnet: 200Gi
    stagenet: 1Ti
    mainnet: 1Ti
  accessMode: ReadWriteOnce
  storageClass: gp3

serviceAccount:
  create: true
  name: "serv-node-hermes"

priorityClassName: ""

podSecurityContext: {}

securityContext: {}

resources:
  requests:
    cpu: 4
    memory: 4Gi
  limits:
    cpu: 8
    memory: 8Gi

nodeSelector: {}

tolerations: []

affinity: {}

global:
  tag:
  net: testnet
  peer:
  passwordSecret:
  mnemonicSecret:
  gateway:
    enabled: false
    name: "hermesnode-gateway"
  images:
    alpineK8s:
      tag: 1.18.2
      hash: 768491682ca99e14498ddb62973a95a664a0525ca18e7ad0eaab2621d3124f5b
    busybox:
      tag: latest
      hash: caa382c432891547782ce7140fb3b7304613d3b0438834dce1cad68896ab110a


