# Default values for hermes node

net: testnet
type: genesis

autoupdate:
  enable: false
  nodes:

signer:
  name: hermesnode
  password: password
  mnemonicSecret: "password"
  passwordSecret: "password"

peer:
seeds:
peerApi:
ethRouterContract:
  testnet: "0xefA28233838f46a80AaaC8c309077a9ba70D123A"

statesync:
  enabled: false
  seed: false
  trustHeight: 0
  trustHash: ""
  rpcServers:
  peer: ""

enableApi: true

debug: true

chainID:
  testnet: hermes-testnet

haltHeight: false

replicaCount: 1

strategyType: Recreate

image:
  repository:
  tag: testnet
  hash:
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: "ClusterIP"
  port:
    api: 1317
    testnet:
      p2p: 26656
      rpc: 26657

persistence:
  enabled: true
  size:
    testnet: 300Gi
  accessMode: ReadWriteOnce

serviceAccount:
  create: true
  name:

priorityClassName: ""

podSecurityContext: {}

securityContext: {}

resources:
  requests:
    cpu: 4
    memory: 4Gi
  limits:

nodeSelector: {}

tolerations: []

affinity: {}

global:
  tag:
  net:
  peer:
  passwordSecret:
  mnemonicSecret:
  gateway:
    enabled: false
    name: ""
  images:
    alpineK8s:
      tag: 1.18.2
      hash: 768491682ca99e14498ddb62973a95a664a0525ca18e7ad0eaab2621d3124f5b
    busybox:
      tag: latest
      hash: caa382c432891547782ce7140fb3b7304613d3b0438834dce1cad68896ab110a


