apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "operator-gateway.fullname" . }}
  labels:
    {{- include "operator-gateway.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.strategyType }}
  selector:
    matchLabels:
      {{- include "operator-gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "operator-gateway.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '9000'
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "operator-gateway.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}

      initContainers:
      - name: init-external-ip
        image: "alpine/k8s:{{ .Values.global.images.alpineK8s.tag }}@sha256:{{ .Values.global.images.alpineK8s.hash }}"
        command: ['/scripts/external-ip.sh', 'false', '{{ include "gateway.fullname" . }}', '{{ include "gateway.fullname" . }}-external-ip']
        volumeMounts:
          - name: scripts
            mountPath: /scripts
      - name: init-keepalive
        image: "busybox:{{ .Values.global.images.busybox.tag }}@sha256:{{ .Values.global.images.busybox.hash }}"
        command:
        - /bin/sh
        - -c
        - |
          sysctl -w net.ipv4.tcp_keepalive_time=120
          sysctl -w net.ipv4.tcp_keepalive_intvl=60
          sysctl -w net.ipv4.tcp_keepalive_probes=3
        securityContext:
          privileged: true
      containers:
        - name: {{ .Chart.Name }}-process
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "operator-gateway.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /var/data/operator-gateway
              name: data
              subPath: data
            - mountPath: /root/.hermesnode
              name: data
              subPath: hermesnode
            - mountPath: /etc/operator-gateway
              name: data
              subPath: etc
          env:
            - name: EXTERNAL_IP
              valueFrom:
                configMapKeyRef:
                  name: {{ include "operator-gateway.fullname" . }}-external-ip
                  key: externalIP
            - name: SEED
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SIGNER_NAME
              value: {{ .Values.signer.name }}
            - name: SIGNER_PASSWD
               {{- if default .Values.signer.passwordSecret .Values.global.passwordSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ default .Values.signer.passwordSecret .Values.global.passwordSecret }}
                  key: password
               {{- else}}
              value: {{ .Values.signer.password }}
               {{- end }}
            {{- if default .Values.signer.mnemonicSecret .Values.global.mnemonicSecret }}
            - name: SIGNER_SEED_PHRASE
              valueFrom:
                secretKeyRef:
                  name: {{ default .Values.signer.mnemonicSecret .Values.global.mnemonicSecret }}
                  key: mnemonic
            {{- end }}
            {{- range $key, $value := .Values.environment }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port.http }}
              protocol: TCP
            - name: grpc
              containerPort: {{ .Values.service.port.grpc }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources.gateway | nindent 12 }}
        - name: {{ .Chart.Name }}-nginx
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.nginx.name }}:{{ .Values.nginx.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- range $key, $value := .Values.environment }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
          ports:
            - name: http-nginx
              containerPort: 80
              protocol: TCP
            - name: token
              containerPort: {{ .Values.service.port.token }}
              protocol: TCP
            - name: sol
              containerPort: {{ .Values.service.port.sol }}
              protocol: TCP
            - name: eth
              containerPort: {{ .Values.service.port.eth }}
              protocol: TCP
            - name: dot
              containerPort: {{ .Values.service.port.dot }}
              protocol: TCP
            - name: btc
              containerPort: {{ .Values.service.port.btc }}
              protocol: TCP
            - name: doj
              containerPort: {{ .Values.service.port.doj }}
              protocol: TCP
          resources:
              {{- toYaml .Values.resources.nginx | nindent 12 }}
      volumes:
      - name: data
      {{- if and .Values.persistence.enabled (not .Values.persistence.hostPath) }}
        persistentVolumeClaim:
          claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ template "operator-gateway.fullname" . }}{{- end }}
      {{- else if and .Values.persistence.enabled .Values.persistence.hostPath }}
        hostPath:
          path: {{ .Values.persistence.hostPath }}
          type: DirectoryOrCreate
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: scripts
        configMap:
          name: {{ include "operator-gateway.fullname" . }}-scripts
          defaultMode: 0777
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
