apiVersion: v1
kind: Service
metadata:
  name: {{ include "operator-gateway.fullname" . }}
  labels:
    {{- include "operator-gateway.labels" . | nindent 4 }}
  annotations:
    # AWS
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    # GCP
    cloud.google.com/l4-rbs: enabled
spec:
  type: {{ .Values.service.type }}
  {{- if ne "ClusterIP" .Values.service.type }}
  externalTrafficPolicy: Local
  {{- end }}
  ports:
    - port: {{ .Values.service.port.http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.port.token }}
      targetPort: token
      protocol: TCP
      name: token
    - port: {{ .Values.service.port.grpc }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.service.port.sol }}
      targetPort: sol
      protocol: TCP
      name: sol
    - port: {{ .Values.service.port.dot }}
      targetPort: dot
      protocol: TCP
      name: dot
    - port: {{ .Values.service.port.eth }}
      targetPort: eth
      protocol: TCP
      name: eth
    - port: {{ .Values.service.port.btc }}
      targetPort: btc
      protocol: TCP
      name: btc
    - port: {{ .Values.service.port.doj }}
      targetPort: doj
      protocol: TCP
      name: doj
  selector:
    {{- include "operator-gateway.selectorLabels" . | nindent 4 }}
