apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bitcoin-daemon.fullname" . }}-scripts
data:
  probe.sh: |
    #!/bin/bash
    set -eo pipefail

    EXTRA_ARGS=""
    if [ "$NET" = "mocknet" ]; then
    EXTRA_ARGS="-regtest"
    elif [ "$NET" = "testnet" ]; then
    EXTRA_ARGS="-testnet"
    fi

    bitcoin-cli -rpcuser=hermeschain \
    -rpcpassword=decbew-3refnY-tywzoj \
    -rpcport=8332 \
    $EXTRA_ARGS ping
