apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
  annotations:
    # AWS
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    # hcloud
    load-balancer.hetzner.cloud/location: nbg1
    load-balancer.hetzner.cloud/use-private-ip: "true"
    load-balancer.hetzner.cloud/disable-private-ingress: "true"
    load-balancer.hetzner.cloud/type: lb11
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: Local
  ports:
    - port: {{ include "gateway-landing-page.http" . }}
      targetPort: landing-page
      protocol: TCP
      name: landing-page
    - port: {{ include "gateway-dojima-wallet.http" . }}
      targetPort: dojima-wallet
      protocol: TCP
      name: dojima-wallet
    - port: {{ include "gateway-dojima-explorer.http" . }}
      targetPort: dojima-explorer
      protocol: TCP
      name: dojima-explorer
  selector:
    {{- include "gateway.selectorLabels" . | nindent 4 }}
