apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
  annotations:
    # AWS
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    # hcloud
    load-balancer.hetzner.cloud/location: nbg1
    load-balancer.hetzner.cloud/use-private-ip: "true"
    load-balancer.hetzner.cloud/disable-private-ingress: "true"
    load-balancer.hetzner.cloud/type: lb11

    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-south-1:576263512135:certificate/7e7c2f73-8cc3-4cc8-a881-2ec497880ac0
    # Only run SSL on the port named "https" below.
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "landing-page"
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: Local
  ports:
    - port: 443
      targetPort: landing-page
      protocol: TCP
      name: landing-page
    - port: {{ include "gateway-dojima-wallet.http" . }}
      targetPort: dojima-wallet
      protocol: TCP
      name: dojima-wallet
    - port: {{ include "gateway-dojima-explorer.http" . }}
      targetPort: dojima-explorer
      protocol: TCP
      name: dojima-explorer
    - port: {{ include "gateway-developer-docs.http" . }}
      targetPort: developer-docs
      protocol: TCP
      name: developer-docs
    - port: {{ include "gateway-faas.http" . }}
      targetPort: faas
      protocol: TCP
      name: faas
  selector:
    {{- include "gateway.selectorLabels" . | nindent 4 }}
