apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
  annotations:
    # AWS
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-south-1:576263512135:certificate/7e7c2f73-8cc3-4cc8-a881-2ec497880ac0
    # Only run SSL on the port named "https" below.
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: Local
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
    - port: {{ include "gateway-dojima-wallet.http" . }}
      targetPort: dojima-wallet
      protocol: TCP
      name: dojima-wallet
    - port: {{ include "gateway-dojima-explorer.http" . }}
      targetPort: dojima-explorer
      protocol: TCP
      name: dojima-explorer
    - port: {{ include "gateway-developer-docs.http" . }}
      targetPort: developer-docs
      protocol: TCP
      name: developer-docs
    - port: {{ include "gateway-faas.http" . }}
      targetPort: faas
      protocol: TCP
      name: faas
    - port: {{ include "gateway-dojima-blockscout.http" . }}
      targetPort: doj-blockscout
      protocol: TCP
      name: doj-blockscout
    {{- if .Values.domain.kubecost.enable }}
    - port: {{ include "gateway-dojima-kubecost.http" . }}
      targetPort: kubecost
      protocol: TCP
      name: kubecost
    {{- end }}
    {{- if .Values.domain.landing_page.enable }}
    - port: {{ include "gateway-landing-page.http" . }}
      targetPort: landing-page
      protocol: TCP
      name: landing-page
    {{- end }}
    {{- if .Values.domain.v2_blockscout.enable }}
    - port: {{ include "gateway-dojima-v2-blockscout-backend.http" . }}
      targetPort: v2-doj-bs-backend
      protocol: TCP
      name: v2-doj-bs-backend
    {{- end }}
    {{- if .Values.domain.v2_blockscout.enable }}
    - port: {{ include "gateway-dojima-v2-blockscout-frontend.http" . }}
      targetPort: v2-doj-bs-frontend
      protocol: TCP
      name: v2-doj-bs-frontend
    {{- end }}
  selector:
    {{- include "gateway.selectorLabels" . | nindent 4 }}
