apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
  annotations:
    # AWS
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: Local
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
    - port: {{ include "gateway-dojima-wallet.http" . }}
      targetPort: dojima-wallet
      protocol: TCP
      name: dojima-wallet
    - port: {{ include "gateway-dojima-explorer.http" . }}
      targetPort: dojima-explorer
      protocol: TCP
      name: dojima-explorer
    - port: {{ include "gateway-developer-docs.http" . }}
      targetPort: developer-docs
      protocol: TCP
      name: developer-docs
    - port: {{ include "gateway-faas.http" . }}
      targetPort: faas
      protocol: TCP
      name: faas
    - port: {{ include "gateway-dojima-blockscout.http" . }}
      targetPort: doj-blockscout
      protocol: TCP
      name: doj-blockscout
  selector:
    {{- include "gateway.selectorLabels" . | nindent 4 }}
