apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "arbitrum_stack.fullname" . }}-scripts
data:
  init_testnode.sh: |
    #!/bin/bash

    # Update and install dependencies
    apt-get update && \
      apt-get install -y git docker.io python3 build-essential curl jq

    # Set up working directory
    mkdir -p /workspace
    cd /workspace
    mkdir /root/l2_config/l1keystore
    # Clone the repository
    git clone --no-checkout https://github.com/dojimanetwork/nitro-testnode.git ./

    git checkout 3086f241adf803367c3a0d03f2019330c3f484c7

    ls -lsart /workspace
    cd /workspace/scripts

    # Install Yarn dependencies and build
    yarn install

  generate_l1keystore.sh: |
    #!/bin/bash
    /scripts/init_testnode.sh
    cp /scripts/generate_l1keystore.js /workspace/scripts
    cd /workspace/scripts
    pwd
    node generate_l1keystore.js

  set_redis_prorities.sh: |
    #!/bin/bash
    /scripts/init_testnode.sh
    cp /scripts/write_redis_properties.js /workspace/scripts
    cd /workspace/scripts
    pwd
    node write_redis_properties.js
    exit 0

  write_l2_chain_config.sh: |
    #!/bin/bash

    CONFIG_PATH="/root/l2_config/"
    mkdir /root/l2_config
    touch /root/l2_config/l2_chain_config.json
    # Define the JSON configuration as a single variable
    l2ChainConfigJSON=$(cat <<EOF
    {
      "chainId": {{ .Values.l2_chain_id }},
      "homesteadBlock": 0,
      "daoForkSupport": true,
      "eip150Block": 0,
      "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
      "eip155Block": 0,
      "eip158Block": 0,
      "byzantiumBlock": 0,
      "constantinopleBlock": 0,
      "petersburgBlock": 0,
      "istanbulBlock": 0,
      "muirGlacierBlock": 0,
      "berlinBlock": 0,
      "londonBlock": 0,
      "clique": {
        "period": 0,
        "epoch": 0
      },
      "arbitrum": {
        "EnableArbOS": true,
        "AllowDebugPrecompiles": true,
        "DataAvailabilityCommittee": false,
        "InitialArbOSVersion": 32,
        "InitialChainOwner": {{ .Values.l2_owner | quote }},
        "GenesisBlockNum": 0
      }
    }
    EOF
    )

    echo "$l2ChainConfigJSON" | jq '.' > "$CONFIG_PATH/l2_chain_config.json"
    ls -lsart $CONFIG_PATH
  sequencer_configs.sh: |
    #!/bin/bash
      set -euo pipefail
      apk add openssl jq

      # Define file paths
      CONFIG_PATH="/root/l2_config" # Update with the correct path
      REDIS_KEY=$REDIS_SIGNER_KEY # Assuming this variable is set
      echo "redis"
      # Generate a JWT secret file
      openssl rand -hex 32 | tr -d "\n" > "$CONFIG_PATH/val_jwt.hex"

      # Base configuration as JSON object
      baseConfig=$(jq -n \
      --arg url "{{ .Values.arbitrum_stack.environment.PARENT_CHAIN_RPC }}" \
      --argjson chain_id "{{ .Values.l2_chain_id }}" \
      --arg account "{{ .Values.l2_owner }}" \
      --arg password "{{ .Values.parent_passphrase }}" \
      --arg config_path "$CONFIG_PATH" \
      --arg sequencer_account "{{ .Values.sequencer_address }}" \
      --arg redis_signing_key "$REDIS_KEY" \
      --arg jwt_secret "$CONFIG_PATH/val_jwt.hex" \
      '{
      "parent-chain": {
        "connection": {
          "url": $url
        }
      },
      "chain": {
        "id": $chain_id,
        "info-files": [
          "\($config_path)/l2_chain_info.json"
        ]
      },
      "node": {
        "staker": {
          "dangerous": {
            "without-block-validator": false
          },
          "parent-chain-wallet": {
            "account": $account,
            "password": $password,
            "pathname": "\($config_path)/l1keystore"
          },
          "disable-challenge": false,
          "enable": false,
          "staker-interval": "10s",
          "make-assertion-interval": "10s",
          "strategy": "MakeNodes"
        },
        "sequencer": true,
        "dangerous": {
          "no-sequencer-coordinator": false,
          "disable-blob-reader": true
        },
        "delayed-sequencer": {
          "enable": true
        },
        "seq-coordinator": {
          "enable": true,
          "redis-url": "redis://127.0.0.1:6379",
          "lockout-duration": "30s",
          "lockout-spare": "1s",
          "my-url": "",
          "retry-interval": "0.5s",
          "seq-num-duration": "24h0m0s",
          "update-interval": "3s"
        },
        "batch-poster": {
          "enable": false,
          "redis-url": "redis://127.0.0.1:6379",
          "max-delay": "30s",
          "l1-block-bound": "ignore",
          "parent-chain-wallet": {
            "account": $sequencer_account,
            "password": $password,
            "pathname": "\($config_path)/l1keystore"
          },
          "data-poster": {
            "redis-signer": {
              "signing-key": $redis_signing_key
            },
            "wait-for-l1-finality": false
          }
        },
        "block-validator": {
          "validation-server": {
            "url": "ws://127.0.0.1:8549",
            "jwtsecret": $jwt_secret
          }
        }
      },
      "execution": {
        "sequencer": {
          "enable": true
        },
        "forwarding-target": "null"
      },
      "persistent": {
        "chain": "local"
      },
      "ws": {
        "addr": "0.0.0.0"
      },
      "http": {
        "addr": "0.0.0.0",
        "vhosts": "*",
        "corsdomain": "*"
      }
    }')

      # Write to the config files
      echo "$baseConfig" | jq '.' > "$CONFIG_PATH/base_config.json"

      # Derived configurations
      validatorConfig=$(echo "$baseConfig" | jq '
      .node.staker.enable = true |
      .node.staker["use-smart-contract-wallet"] = true
      ')
      echo "$validatorConfig" > "$CONFIG_PATH/validator_config.json"

    unsafeStakerConfig=$(echo "$validatorConfig" | jq '
      .node.staker.dangerous["without-block-validator"] = true
      ')
    echo "$unsafeStakerConfig" > "$CONFIG_PATH/unsafe_staker_config.json"

    sequencerConfig=$(echo "$baseConfig" | jq '
      .node.sequencer = true |
      .node["seq-coordinator"].enable = true |
      .execution.sequencer.enable = true |
      .node["delayed-sequencer"].enable = true
      ')
    echo "$sequencerConfig" > "$CONFIG_PATH/sequencer_config.json"

    posterConfig=$(echo "$baseConfig" | jq '
      .node["seq-coordinator"].enable = true |
      .node["batch-poster"].enable = true
      ')
    echo "$posterConfig" > "$CONFIG_PATH/poster_config.json"

    ls -lsart $CONFIG_PATH

  deploy_rollup_contracts.sh: |
      #!/bin/bash

      set -euo pipefail

      # Install necessary dependencies
       apt-get update && \
      apt-get install -y git docker.io python3 build-essential curl jq

      # Define file paths
      CONFIG_PATH="/root/l2_config"
      DEVELOPMENT_JSON="$CONFIG_PATH/deployment.json"

      # Ensure the CONFIG_PATH directory exists
      mkdir -p "$CONFIG_PATH"

      # Generate a JWT secret file
      openssl rand -hex 32 | tr -d "\n" > "$CONFIG_PATH/val_jwt.hex"

      # Check if deployment.json exists
      if [ -f "$DEVELOPMENT_JSON" ]; then
        echo "deployment.json exists. Checking for null values..."

        # Check if any values in the JSON are null
        null_values=$(jq 'to_entries | map(select(.value == null)) | .[] | .key' "$DEVELOPMENT_JSON" || true)

        if [ -z "$null_values" ]; then
          echo "Contracts are already deployed, so skipping the setup."
          cat "$DEVELOPMENT_JSON"
          exit 0 # Exit with success
        else
          echo "Some values in deployment.json are null. Proceeding with deployment."
          echo "Keys with null values:"
          echo "$null_values"
        fi
      else
        echo "deployment.json does not exist. Proceeding with deployment."
      fi

      # Set up working directory
      WORKSPACE_DIR="/workspace"
      mkdir -p "$WORKSPACE_DIR"
      cd "$WORKSPACE_DIR"

      # Clone the repository without checking out any files
      git clone --no-checkout https://github.com/dojimanetwork/nitro-contracts.git ./

      # Checkout the specified branch
      if [ -z "${NITRO_CONTRACTS_BRANCH:-}" ]; then
        echo "Error: NITRO_CONTRACTS_BRANCH environment variable is not set."
        exit 1
      fi

      git checkout "$NITRO_CONTRACTS_BRANCH"

      # Install Foundry
      curl -L https://foundry.paradigm.xyz | bash

      # Add Foundry to PATH
      export PATH="${PATH}:/root/.foundry/bin"

      # Update Foundry tools
      foundryup

      # Ensure scripts directory exists and create config.ts
      mkdir -p scripts
      touch scripts/config.ts

      # Install Yarn dependencies and build
      yarn install
      yarn build:all

      # Run the create-rollup-testnode script
      yarn run create-rollup-testnode

      # List files for verification
      ls -lsart


  external-ip.sh: |
    #!/bin/bash
    # ./external-ip.sh <host_network> <service_name> <config_map>
    #
    # Script to extract external ip from a service:
    # If host network returns public ip of the node
    # If LoadBalancer returns external IP either directly or from hostname
    # If ClusterIP return service IP
    # If NodePort returns node IP

    apk add bind-tools

    HOST_NETWORK=$1
    SERVICE=$2
    CONFIGMAP=$3

    if [ "$HOST_NETWORK" = "true" ]; then
      external_ip=$(curl -s http://whatismyip.akamai.com)
    else
      type=$(kubectl get svc "$SERVICE" -o jsonpath='{.spec.type}')
      external_ip=""

      if [ "$type" = "ClusterIP" ]; then
        external_ip=$(kubectl get svc "$SERVICE" -o jsonpath='{.spec.clusterIP}')
      elif [ "$type" = "NodePort" ]; then
        external_ip=$(kubectl get nodes --selector=kubernetes.io/role!=master -o jsonpath='{.items[0].status.addresses[?(@.type=="ExternalIP")].address}')
      elif [ "$type" = "LoadBalancer" ]; then
        # Hack TODO remove when this is fixed here https://github.com/kubernetes/kubernetes/issues/82595
        kubectl annotate svc "$SERVICE" service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled=false --overwrite
        sleep 5
        kubectl annotate svc "$SERVICE" service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled=true --overwrite

        while [ -z "$external_ip" ]; do
          echo "Waiting for load balancer external endpoint..."
          external_ip=$(kubectl get svc "$SERVICE" -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          if [ -z "$external_ip" ]; then
            hostname=$(kubectl get svc "$SERVICE" -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
            [ -n "$hostname" ] && external_ip=$(dig +short "$hostname" | sort | head -1)
          fi
          [ -z "$external_ip" ] && sleep 10
        done
      fi
    fi

    kubectl create configmap "$CONFIGMAP" --from-literal=externalIP="$external_ip" --dry-run=client -o yaml | kubectl apply -f -


  generate_l1keystore.js: |
    const { ethers } = require("ethers");
    const fs = require("fs");
    const path = require("path");

    const configPath = "/root/l2_config/l1keystore";

    async function create() {
      try {
      // Ensure the directory exists
        if (!fs.existsSync(configPath)) {
            fs.mkdirSync(configPath, { recursive: true, mode: 0o755 });
            console.log(`Directory created: ${configPath} with permissions 755`);
        }

        const accounts = [process.env.DEPLOYER_PRIVKEY, process.env.SEQUENCER_PRIVKEY];
        const passphrase = process.env.PARENT_PASSPHRASE;

        for (let i = 0; i < accounts.length; i++) {
            const wallet = new ethers.Wallet(accounts[i]);
            const walletJSON = await wallet.encrypt(passphrase);
            try{
              fs.writeFileSync(
                path.join(configPath, `${wallet.address}.key`),
                walletJSON
              );
            }catch (error) {
                console.error("Error creating file:", error);
            }
            console.log(`Wallet for ${wallet.address} saved.`);
          }
        } catch (error) {
            console.error("Error creating wallets:", error);
        }
    }

    create();
  write_redis_properties.js: |
    const {
      createClient,
    } = require("@node-redis/client")

    async function getAndPrint(
      redis,
      key
      ) {
      const val = await redis.get(key);
      console.log("redis[%s]:%s", key, val);
    }

    async function writeRedisPriorities(redisUrl = "redis://localhost:6379") {
      const redis = createClient({ url: redisUrl });
      let priostring = "ws://localhost:8548";
      await redis.connect();

      await redis.set("coordinator.priorities", priostring);

      await getAndPrint(redis, "coordinator.priorities");
    }

    writeRedisPriorities("redis://localhost:6379")

