{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "arbitrum_stack.serviceAccountName" . }}
  labels:
{{ include "arbitrum_stack.labels" . | nindent 4 }}
{{- end -}}
