apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-{{ include "arbitrum_stack.name" . }}
  namespace: prometheus-system
  labels:
{{- include "arbitrum_stack.labels" . | nindent 4 }}
    release: prometheus
spec:
  selector:
    matchLabels:
{{- include "arbitrum_stack.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  endpoints:
  - port: prometheus
    interval: 15s
