kind: PersistentVolume
apiVersion: v1
metadata:
  name: hermes-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: aws://ap-south-1c/vol-0ec973e760286eb33
    fsType: ext4
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  volumeMode: Filesystem