kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Values.persistence.name }}
spec:
  capacity:
    {{- if eq (include "hermesnode.net" .) "mainnet" }}
    storage: {{ .Values.persistence.size.mainnet | quote }}
    {{- else if eq (include "hermesnode.net" .) "stagenet" }}
    storage: {{ .Values.persistence.size.stagenet | quote }}
    {{- else }}
    storage: {{ .Values.persistence.size.testnet | quote }}
    {{- end }}
  accessModes:
  - ReadWriteOnce
  csi:
    driver: pd.csi.storage.gke.io
    fsType: ext4
    volumeHandle: projects/prod-dojima/regions/asia-south1/disks/{{ .Values.persistence.name }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp3
  volumeMode: Filesystem