apiVersion: v1
kind: Service
metadata:
  name: {{ include "hermesnode.fullname" . }}
  labels:
    {{- include "hermesnode.labels" . | nindent 4 }}
  annotations:
    # AWS
    #service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    #service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    #service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    #service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: {{ .Values.service.type }}
  {{- if ne "ClusterIP" .Values.service.type }}
  externalTrafficPolicy: Local
  {{- end }}
  ports:
    - name: api
      port: {{ .Values.service.port.api }}
      targetPort: api
      protocol: TCP
    - name: p2p
      port: {{ include "hermesnode.p2p" . }}
      targetPort: p2p
      protocol: TCP
    - name: rpc
      port: {{ include "hermesnode.rpc" . }}
      targetPort: rpc
      protocol: TCP
    - name: grpc
      port: {{ include "hermesnode.grpc" . }}
      targetPort: grpc
      protocol: TCP
    - name: abci
      port: {{ include "hermesnode.abci" . }}
      protocol: TCP
      targetPort: abci
    - name: prom-collector
      port: {{ include "hermesnode.prometheus_collector" . }}
      targetPort: prom-collector
      protocol: TCP
    - name: grpc-web
      port: {{ include "hermesnode.grpc-web" . }}
      targetPort: grpc-web
      protocol: TCP
    - name: pprof
      port:  {{ include "hermesnode.pprof" . }}
      targetPort: pprof
      protocol: TCP
    - name: rosetta
      port:  {{ include "hermesnode.rosetta" . }}
      targetPort: rosetta
      protocol: TCP
  selector:
    {{- include "hermesnode.selectorLabels" . | nindent 4 }}
