kind: PersistentVolume
apiVersion: v1
metadata:
  name: ethereum-backup-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: aws://ap-south-1a/vol-042f65ae30fa2a559
    fsType: ext4
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp3
  volumeMode: Filesystem