kind: PersistentVolume
apiVersion: v1
metadata:
  name: binance-backup-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: aws://ap-south-1b/vol-0060ceff2ddaa1e94
    fsType: ext4
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp3
  volumeMode: Filesystem