kind: PersistentVolume
apiVersion: v1
metadata:
  name: hermes-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: aws://ap-south-1c/vol-0dd745a8b71142bb7
    fsType: ext4
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp3
  volumeMode: Filesystem