kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ template "hello-word.fullname" . }}
  labels:
    type: amazonEBS
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-0778a2ca059680bb2
    fsType: ext4
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2