kind: PersistentVolume
apiVersion: v1
metadata:
  name: narada-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: aws://ap-south-1b/vol-09b55f7ba26e61740
    fsType: ext4
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  volumeMode: Filesystem