kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ template "hello-word.fullname" . }}-pv
spec:
  capacity:
    storage: 300Gi
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: aws://ap-south-1c/vol-005f870643bbcb26a
    fsType: ext4
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp3
  volumeMode: Filesystem