kind: PersistentVolume
apiVersion: v1
metadata:
  name: hermes-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  csi:
    driver: pd.csi.storage.gke.io
    fsType: ext4
    volumeHandle: projects/prod-dojima/regions/asia-south1/disks/dojima-chain-pv
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp3
  volumeMode: Filesystem