apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-word.fullname" . }}
  labels:
    {{- include "hello-word.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  selector:
    {{- include "hello-word.selectorLabels" . | nindent 4 }}
