apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-word.fullname" . }}
  labels:
    {{- include "hello-word.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: api
      port: {{ include "hello-word.api" . }}
      targetPort: api
      protocol: TCP
  selector:
    {{- include "hello-word.selectorLabels" . | nindent 4 }}
